//! Harness definitions — the tooling that runs on top of a host.
//!
//! A harness renders training configuration (YAML, Python script) from canonical
//! `TrainingParams`. Hosts bind a harness and use it to generate the config/script
//! they dispatch to their compute backend.
//!
//! Harness → Host mapping:
//!   Axolotl → Runpod

use crate::providers::types::*;
use std::path::PathBuf;

// ── HarnessAdapter trait ───────────────────────────────────────────────────

/// Renders training configuration in a harness-specific format.
///
/// The *harness* is the tooling that orchestrates training (axolotl CLI,
/// unsloth Python, TRL SFTTrainer). The *host* is where compute runs.
/// Each host binds exactly one harness; the harness generates the config
/// or script that the host dispatches.
///
/// pre:  job.params carries full expanded TrainingParams
/// post: returns harness-native config string (YAML, Python script, etc.)
///
/// MDS: Composition — CAN render_config ON TrainingJob VIA HarnessAdapter
pub trait HarnessAdapter: Send + Sync {
    /// Render the training configuration in the harness's native format.
    fn render_config(&self, job: &TrainingJob) -> Result<String, ProviderError>;

    /// Directory where the harness outputs adapter weights.
    fn output_dir(&self, job_id: &str) -> PathBuf;

    /// File whose existence signals training completion.
    fn completion_marker(&self, job_id: &str) -> PathBuf;

    /// The harness identifier for CNS spans.
    fn harness_id(&self) -> TrainingHarnessId;
}

// ── Axolotl harness ────────────────────────────────────────────────────────

/// Renders axolotl YAML configuration from canonical TrainingParams.
pub struct AxolotlHarness;

impl HarnessAdapter for AxolotlHarness {
    fn render_config(&self, job: &TrainingJob) -> Result<String, ProviderError> {
        let p = &job.params;
        let lo = &p.lora;
        let q = &p.quantization;
        let opt = &p.optimization;
        let seq = &p.sequence;
        let adv = &p.advanced;

        let mut yaml = String::new();
        yaml.push_str("# Auto-generated by hKask Training Server (harness: axolotl)\n");
        yaml.push_str(&format!("base_model: {}\n", job.base_model));
        yaml.push_str("datasets:\n");
        yaml.push_str(&format!("  - path: {}\n", job.dataset_path.display()));
        yaml.push_str("    type: chatml\n");
        yaml.push_str(&format!(
            "output_dir: {}\n",
            self.output_dir(&job.id).display()
        ));
        yaml.push_str(&format!("num_epochs: {}\n", p.num_epochs));
        yaml.push_str(&format!("micro_batch_size: {}\n", p.batch_size));
        yaml.push_str(&format!("learning_rate: {:.6}\n", p.learning_rate));
        yaml.push_str("adapter: lora\n");
        yaml.push_str(&format!("lora_r: {}\n", lo.r));
        yaml.push_str(&format!("lora_alpha: {}\n", lo.alpha));
        yaml.push_str(&format!("lora_dropout: {}\n", lo.dropout));
        yaml.push_str("lora_target_modules:\n");
        for m in &lo.target_modules {
            yaml.push_str(&format!("  - {}\n", m));
        }
        if !lo.modules_to_save.is_empty() {
            yaml.push_str("lora_modules_to_save:\n");
            for m in &lo.modules_to_save {
                yaml.push_str(&format!("  - {}\n", m));
            }
        }
        if lo.use_rslora {
            yaml.push_str("peft_use_rslora: true\n");
        }
        if lo.use_dora {
            yaml.push_str("peft_use_dora: true\n");
        }
        if let Some(ref init) = lo.init_lora_weights {
            yaml.push_str(&format!(
                "peft_init_lora_weights: {}\n",
                init.as_config_value()
            ));
        }
        if lo.bias != crate::providers::types::LoraBias::None {
            yaml.push_str(&format!(
                "peft_bias: {}\n",
                match lo.bias {
                    crate::providers::types::LoraBias::All => "all",
                    crate::providers::types::LoraBias::LoraOnly => "lora_only",
                    crate::providers::types::LoraBias::None => "none",
                }
            ));
        }

        // Quantization
        if q.load_in_4bit {
            yaml.push_str("load_in_4bit: true\n");
            if let Some(ref dt) = q.bnb_4bit_compute_dtype {
                yaml.push_str(&format!("bnb_4bit_compute_dtype: {}\n", dt));
            }
            if let Some(ref qt) = q.bnb_4bit_quant_type {
                yaml.push_str(&format!("bnb_4bit_quant_type: {}\n", qt));
            }
            if q.bnb_4bit_use_double_quant {
                yaml.push_str("bnb_4bit_use_double_quant: true\n");
            }
        } else if q.load_in_8bit {
            yaml.push_str("load_in_8bit: true\n");
        }

        // Optimizer & scheduler
        if let Some(ref optimizer) = opt.optimizer {
            yaml.push_str(&format!("optimizer: {}\n", optimizer));
        }
        if opt.weight_decay > 0.0 {
            yaml.push_str(&format!("weight_decay: {}\n", opt.weight_decay));
        }
        if opt.gradient_accumulation_steps > 1 {
            yaml.push_str(&format!(
                "gradient_accumulation_steps: {}\n",
                opt.gradient_accumulation_steps
            ));
        }
        if let Some(ref sched) = opt.lr_scheduler {
            yaml.push_str(&format!("lr_scheduler: {}\n", sched));
        }
        if let Some(ws) = opt.warmup_steps {
            yaml.push_str(&format!("warmup_steps: {}\n", ws));
        } else if let Some(wr) = opt.warmup_ratio {
            yaml.push_str(&format!("warmup_ratio: {}\n", wr));
        }
        if let Some(mgn) = opt.max_grad_norm {
            yaml.push_str(&format!("max_grad_norm: {}\n", mgn));
        }

        // Sequence
        if let Some(sl) = seq.sequence_len {
            yaml.push_str(&format!("sequence_len: {}\n", sl));
        }
        if seq.sample_packing {
            yaml.push_str("sample_packing: true\n");
        }
        if seq.pad_to_sequence_len {
            yaml.push_str("pad_to_sequence_len: true\n");
        }
        if let Some(na) = seq.neftune_noise_alpha {
            yaml.push_str(&format!("neftune_noise_alpha: {}\n", na));
        }

        // Advanced
        if let Some(ref attn) = adv.attn_implementation {
            yaml.push_str(&format!("attn_implementation: {}\n", attn));
        }
        if let Some(ref gc) = adv.gradient_checkpointing {
            yaml.push_str(&format!("gradient_checkpointing: {}\n", gc));
        }
        if adv.bf16 {
            yaml.push_str("bf16: true\n");
        } else if adv.fp16 {
            yaml.push_str("fp16: true\n");
        }
        if let Some(esr) = adv.eval_split_ratio {
            yaml.push_str(&format!("eval_split_ratio: {}\n", esr));
        }

        Ok(yaml)
    }

    fn output_dir(&self, job_id: &str) -> PathBuf {
        PathBuf::from(format!("./axolotl-output/{}", job_id))
    }

    fn completion_marker(&self, job_id: &str) -> PathBuf {
        self.output_dir(job_id).join("adapter_model.safetensors")
    }

    fn harness_id(&self) -> TrainingHarnessId {
        TrainingHarnessId::Axolotl
    }
}
