//! Harness definitions — the tooling that runs on top of a host.
//!
//! A harness renders training configuration (YAML, Python script) from canonical
//! `TrainingParams`. Hosts bind a harness and use it to generate the config/script
//! they dispatch to their compute backend.
//!
//! Harness → Host mapping:
//!   Axolotl → Together AI, Runpod
//!   Unsloth → Baseten

use crate::providers::types::*;
use std::path::PathBuf;

// ── Harness capability enumeration ───────────────────────────────────

/// Harness capabilities — features that a training harness supports.
/// Used for capability filtering when generating provider-specific config
/// from canonical `TrainingParams`.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum HarnessCapability {
    Qlora4bit,
    Qlora8bit,
    DoubleQuant,
    RsLora,
    SequencePacking,
    Neftune,
    FlashAttention2,
    FlashAttention3,
    Sdpa,
    GradientCheckpointing,
    Fp8Mixed,
    DeepSpeed,
    Fsdp,
    SampleGeneration,
    LoraPlus,
}

impl HarnessCapability {
    pub fn cns_span(&self) -> &'static str {
        match self {
            HarnessCapability::Qlora4bit => "cns.training.harness.qlora_4bit",
            HarnessCapability::Qlora8bit => "cns.training.harness.qlora_8bit",
            HarnessCapability::DoubleQuant => "cns.training.harness.double_quant",
            HarnessCapability::RsLora => "cns.training.harness.rslora",
            HarnessCapability::SequencePacking => "cns.training.harness.sequence_packing",
            HarnessCapability::Neftune => "cns.training.harness.neftune",
            HarnessCapability::FlashAttention2 => "cns.training.harness.flash_attn2",
            HarnessCapability::FlashAttention3 => "cns.training.harness.flash_attn3",
            HarnessCapability::Sdpa => "cns.training.harness.sdpa",
            HarnessCapability::GradientCheckpointing => "cns.training.harness.grad_ckpt",
            HarnessCapability::Fp8Mixed => "cns.training.harness.fp8_mixed",
            HarnessCapability::DeepSpeed => "cns.training.harness.deepspeed",
            HarnessCapability::Fsdp => "cns.training.harness.fsdp",
            HarnessCapability::SampleGeneration => "cns.training.harness.sample_gen",
            HarnessCapability::LoraPlus => "cns.training.harness.loraplus",
        }
    }
}

// ── HarnessAdapter trait ───────────────────────────────────────────────────

/// Renders training configuration in a harness-specific format.
///
/// The *harness* is the tooling that orchestrates training (axolotl CLI,
/// unsloth Python, TRL SFTTrainer). The *host* is where compute runs.
/// Each host binds exactly one harness; the harness generates the config
/// or script that the host dispatches.
///
/// pre:  job.params carries full expanded TrainingParams
/// post: returns harness-native config string (YAML, Python script, etc.)
///
/// MDS: Composition — CAN render_config ON TrainingJob VIA HarnessAdapter
pub trait HarnessAdapter: Send + Sync {
    /// Render the training configuration in the harness's native format.
    fn render_config(&self, job: &TrainingJob) -> Result<String, ProviderError>;

    /// Directory where the harness outputs adapter weights.
    fn output_dir(&self, job_id: &str) -> PathBuf;

    /// File whose existence signals training completion.
    fn completion_marker(&self, job_id: &str) -> PathBuf;

    /// The harness identifier for CNS spans.
    fn harness_id(&self) -> TrainingHarnessId;
}

// ── Axolotl harness ────────────────────────────────────────────────────────

/// Renders axolotl YAML configuration from canonical TrainingParams.
pub struct AxolotlHarness;

impl HarnessAdapter for AxolotlHarness {
    fn render_config(&self, job: &TrainingJob) -> Result<String, ProviderError> {
        let p = &job.params;
        let lo = &p.lora;
        let q = &p.quantization;
        let opt = &p.optimization;
        let seq = &p.sequence;
        let adv = &p.advanced;

        let mut yaml = String::new();
        yaml.push_str("# Auto-generated by hKask Training Server (harness: axolotl)\n");
        yaml.push_str(&format!("base_model: {}\n", job.base_model));
        yaml.push_str("datasets:\n");
        yaml.push_str(&format!("  - path: {}\n", job.dataset_path.display()));
        yaml.push_str("    type: chatml\n");
        yaml.push_str(&format!(
            "output_dir: {}\n",
            self.output_dir(&job.id).display()
        ));
        yaml.push_str(&format!("num_epochs: {}\n", p.num_epochs));
        yaml.push_str(&format!("micro_batch_size: {}\n", p.batch_size));
        yaml.push_str(&format!("learning_rate: {:.6}\n", p.learning_rate));
        yaml.push_str("adapter: lora\n");
        yaml.push_str(&format!("lora_r: {}\n", lo.r));
        yaml.push_str(&format!("lora_alpha: {}\n", lo.alpha));
        yaml.push_str(&format!("lora_dropout: {}\n", lo.dropout));
        yaml.push_str("lora_target_modules:\n");
        for m in &lo.target_modules {
            yaml.push_str(&format!("  - {}\n", m));
        }
        if !lo.modules_to_save.is_empty() {
            yaml.push_str("lora_modules_to_save:\n");
            for m in &lo.modules_to_save {
                yaml.push_str(&format!("  - {}\n", m));
            }
        }
        if lo.use_rslora {
            yaml.push_str("use_rslora: true\n");
        }

        // Quantization
        if q.load_in_4bit {
            yaml.push_str("load_in_4bit: true\n");
            if let Some(ref dt) = q.bnb_4bit_compute_dtype {
                yaml.push_str(&format!("bnb_4bit_compute_dtype: {}\n", dt));
            }
            if let Some(ref qt) = q.bnb_4bit_quant_type {
                yaml.push_str(&format!("bnb_4bit_quant_type: {}\n", qt));
            }
            if q.bnb_4bit_use_double_quant {
                yaml.push_str("bnb_4bit_use_double_quant: true\n");
            }
        } else if q.load_in_8bit {
            yaml.push_str("load_in_8bit: true\n");
        }

        // Optimizer & scheduler
        if let Some(ref optimizer) = opt.optimizer {
            yaml.push_str(&format!("optimizer: {}\n", optimizer));
        }
        if opt.weight_decay > 0.0 {
            yaml.push_str(&format!("weight_decay: {}\n", opt.weight_decay));
        }
        if opt.gradient_accumulation_steps > 1 {
            yaml.push_str(&format!(
                "gradient_accumulation_steps: {}\n",
                opt.gradient_accumulation_steps
            ));
        }
        if let Some(ref sched) = opt.lr_scheduler {
            yaml.push_str(&format!("lr_scheduler: {}\n", sched));
        }
        if let Some(ws) = opt.warmup_steps {
            yaml.push_str(&format!("warmup_steps: {}\n", ws));
        } else if let Some(wr) = opt.warmup_ratio {
            yaml.push_str(&format!("warmup_ratio: {}\n", wr));
        }
        if let Some(mgn) = opt.max_grad_norm {
            yaml.push_str(&format!("max_grad_norm: {}\n", mgn));
        }

        // Sequence
        if let Some(sl) = seq.sequence_len {
            yaml.push_str(&format!("sequence_len: {}\n", sl));
        }
        if seq.sample_packing {
            yaml.push_str("sample_packing: true\n");
        }
        if seq.pad_to_sequence_len {
            yaml.push_str("pad_to_sequence_len: true\n");
        }
        if let Some(na) = seq.neftune_noise_alpha {
            yaml.push_str(&format!("neftune_noise_alpha: {}\n", na));
        }

        // Advanced
        if let Some(ref attn) = adv.attn_implementation {
            yaml.push_str(&format!("attn_implementation: {}\n", attn));
        }
        if let Some(ref gc) = adv.gradient_checkpointing {
            yaml.push_str(&format!("gradient_checkpointing: {}\n", gc));
        }
        if adv.bf16 {
            yaml.push_str("bf16: true\n");
        } else if adv.fp16 {
            yaml.push_str("fp16: true\n");
        }
        if let Some(esr) = adv.eval_split_ratio {
            yaml.push_str(&format!("eval_split_ratio: {}\n", esr));
        }

        Ok(yaml)
    }

    fn output_dir(&self, job_id: &str) -> PathBuf {
        PathBuf::from(format!("./axolotl-output/{}", job_id))
    }

    fn completion_marker(&self, job_id: &str) -> PathBuf {
        self.output_dir(job_id).join("adapter_model.safetensors")
    }

    fn harness_id(&self) -> TrainingHarnessId {
        TrainingHarnessId::Axolotl
    }
}

// ── Unsloth harness ────────────────────────────────────────────────────────

/// Renders unsloth Python training script from canonical TrainingParams.
pub struct UnslothHarness;

impl HarnessAdapter for UnslothHarness {
    fn render_config(&self, job: &TrainingJob) -> Result<String, ProviderError> {
        let p = &job.params;
        let lo = &p.lora;
        let q = &p.quantization;
        let opt = &p.optimization;
        let seq = &p.sequence;
        let adv = &p.advanced;

        let target_modules_str = lo
            .target_modules
            .iter()
            .map(|m| format!("\"{}\"", m))
            .collect::<Vec<_>>()
            .join(", ");

        let mut script = String::new();
        script.push_str("# Auto-generated by hKask Training Server (harness: unsloth)\n");
        script.push_str("import torch\n");
        script.push_str("from unsloth import FastLanguageModel\n");
        script.push_str("from datasets import load_dataset\n\n");

        // Model loading with quantization
        let load_kwargs = if q.load_in_4bit {
            ", load_in_4bit=True"
        } else {
            ""
        };
        let max_seq = seq.sequence_len.unwrap_or(2048);
        script.push_str(&format!(
            "model, tokenizer = FastLanguageModel.from_pretrained(\n    model_name=\"{}\",\n    max_seq_length={}{},\n)\n\n",
            job.base_model, max_seq, load_kwargs
        ));

        // PEFT config
        let grad_ckpt = adv.gradient_checkpointing.as_deref().unwrap_or("unsloth");
        script.push_str("model = FastLanguageModel.get_peft_model(\n    model,\n");
        script.push_str(&format!("    r={},\n", lo.r));
        script.push_str(&format!("    lora_alpha={},\n", lo.alpha));
        script.push_str(&format!("    target_modules=[{}],\n", target_modules_str));
        script.push_str(&format!("    lora_dropout={},\n", lo.dropout));
        script.push_str("    bias=\"none\",\n");
        script.push_str(&format!(
            "    use_gradient_checkpointing=\"{}\",\n",
            grad_ckpt
        ));
        if lo.use_rslora {
            script.push_str("    use_rslora=True,\n");
        }
        script.push_str(")\n\n");

        // Dataset
        script.push_str(&format!(
            "dataset = load_dataset(\"json\", data_files=\"{}\", split=\"train\")\n\n",
            job.dataset_path.display()
        ));

        // TrainingArguments
        script.push_str("from transformers import TrainingArguments\n");
        script.push_str("from trl import SFTTrainer\n\n");
        script.push_str("trainer = SFTTrainer(\n    model=model,\n    tokenizer=tokenizer,\n    train_dataset=dataset,\n    dataset_text_field=\"text\",\n");
        script.push_str(&format!("    max_seq_length={},\n", max_seq));
        script.push_str("    args=TrainingArguments(\n");
        script.push_str(&format!(
            "        per_device_train_batch_size={},\n",
            p.batch_size
        ));
        script.push_str(&format!("        num_train_epochs={},\n", p.num_epochs));
        script.push_str(&format!("        learning_rate={},\n", p.learning_rate));
        if let Some(ref sched) = opt.lr_scheduler {
            script.push_str(&format!("        lr_scheduler_type=\"{}\",\n", sched));
        }
        if let Some(wr) = opt.warmup_ratio {
            script.push_str(&format!("        warmup_ratio={},\n", wr));
        }
        if opt.weight_decay > 0.0 {
            script.push_str(&format!("        weight_decay={},\n", opt.weight_decay));
        }
        if opt.gradient_accumulation_steps > 1 {
            script.push_str(&format!(
                "        gradient_accumulation_steps={},\n",
                opt.gradient_accumulation_steps
            ));
        }
        if adv.bf16 {
            script.push_str("        bf16=True,\n");
        } else if adv.fp16 {
            script.push_str("        fp16=True,\n");
        }
        if let Some(esr) = adv.eval_split_ratio {
            script.push_str("        eval_strategy=\"steps\",\n");
            script.push_str(&format!("        eval_steps={},\n", (100.0 / esr) as u32));
        }
        script.push_str(&format!(
            "        output_dir=\"{}\",\n",
            self.output_dir(&job.id).display()
        ));
        script.push_str("    ),\n");
        if seq.sample_packing {
            script.push_str("    packing=True,\n");
        }
        if let Some(na) = seq.neftune_noise_alpha {
            script.push_str(&format!("    neftune_noise_alpha={},\n", na));
        }
        script.push_str(")\n\n");

        script.push_str("trainer.train()\n");
        script.push_str(&format!(
            "model.save_pretrained(\"{}\")\n",
            self.completion_marker(&job.id)
                .parent()
                .expect("completion marker always has a parent directory")
                .display()
        ));

        Ok(script)
    }

    fn output_dir(&self, job_id: &str) -> PathBuf {
        PathBuf::from(format!("./unsloth-output/{}", job_id))
    }

    fn completion_marker(&self, job_id: &str) -> PathBuf {
        self.output_dir(job_id)
            .join("adapter")
            .join("adapter_model.safetensors")
    }

    fn harness_id(&self) -> TrainingHarnessId {
        TrainingHarnessId::Unsloth
    }
}
