//! Harness definitions — the tooling that runs on top of a host.
//!
//! A harness renders training configuration (YAML, Python script) from canonical
//! `TrainingParams`. Hosts bind a harness and use it to generate the config/script
//! they dispatch to their compute backend.
//!
//! Harness → Host mapping:
//!   Axolotl → Together AI, Runpod
//!   Unsloth → Baseten

use crate::providers::types::*;
use std::path::PathBuf;

// ── Harness capability enumeration ───────────────────────────────────

/// Harness capabilities — features that a training harness supports.
/// Used for capability filtering when generating provider-specific config
/// from canonical `TrainingParams`.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum HarnessCapability {
    Qlora4bit,
    Qlora8bit,
    DoubleQuant,
    RsLora,
    SequencePacking,
    Neftune,
    FlashAttention2,
    FlashAttention3,
    Sdpa,
    GradientCheckpointing,
    Fp8Mixed,
    DeepSpeed,
    Fsdp,
    SampleGeneration,
    LoraPlus,
}

impl HarnessCapability {
    pub fn cns_span(&self) -> &'static str {
        match self {
            HarnessCapability::Qlora4bit => "cns.training.harness.qlora_4bit",
            HarnessCapability::Qlora8bit => "cns.training.harness.qlora_8bit",
            HarnessCapability::DoubleQuant => "cns.training.harness.double_quant",
            HarnessCapability::RsLora => "cns.training.harness.rslora",
            HarnessCapability::SequencePacking => "cns.training.harness.sequence_packing",
            HarnessCapability::Neftune => "cns.training.harness.neftune",
            HarnessCapability::FlashAttention2 => "cns.training.harness.flash_attn2",
            HarnessCapability::FlashAttention3 => "cns.training.harness.flash_attn3",
            HarnessCapability::Sdpa => "cns.training.harness.sdpa",
            HarnessCapability::GradientCheckpointing => "cns.training.harness.grad_ckpt",
            HarnessCapability::Fp8Mixed => "cns.training.harness.fp8_mixed",
            HarnessCapability::DeepSpeed => "cns.training.harness.deepspeed",
            HarnessCapability::Fsdp => "cns.training.harness.fsdp",
            HarnessCapability::SampleGeneration => "cns.training.harness.sample_gen",
            HarnessCapability::LoraPlus => "cns.training.harness.loraplus",
        }
    }
}

// ── HarnessAdapter trait ───────────────────────────────────────────────────

/// Renders training configuration in a harness-specific format.
///
/// The *harness* is the tooling that orchestrates training (axolotl CLI,
/// unsloth Python, TRL SFTTrainer). The *host* is where compute runs.
/// Each host binds exactly one harness; the harness generates the config
/// or script that the host dispatches.
///
/// pre:  job.params carries full expanded TrainingParams
/// post: returns harness-native config string (YAML, Python script, etc.)
///
/// MDS: Composition — CAN render_config ON TrainingJob VIA HarnessAdapter
pub trait HarnessAdapter: Send + Sync {
    /// Render the training configuration in the harness's native format.
    fn render_config(&self, job: &TrainingJob) -> Result<String, ProviderError>;

    /// Directory where the harness outputs adapter weights.
    fn output_dir(&self, job_id: &str) -> PathBuf;

    /// File whose existence signals training completion.
    fn completion_marker(&self, job_id: &str) -> PathBuf;

    /// The harness identifier for CNS spans.
    fn harness_id(&self) -> TrainingHarnessId;
}

// ── Axolotl harness ────────────────────────────────────────────────────────

/// Renders axolotl YAML configuration from canonical TrainingParams.
pub struct AxolotlHarness;

impl HarnessAdapter for AxolotlHarness {
    fn render_config(&self, job: &TrainingJob) -> Result<String, ProviderError> {
        let p = &job.params;
        let lo = &p.lora;
        let q = &p.quantization;
        let opt = &p.optimization;
        let seq = &p.sequence;
        let adv = &p.advanced;

        let mut yaml = String::new();
        yaml.push_str("# Auto-generated by hKask Training Server (harness: axolotl)\n");
        yaml.push_str(&format!("base_model: {}\n", job.base_model));
        yaml.push_str("datasets:\n");
        yaml.push_str(&format!("  - path: {}\n", job.dataset_path.display()));
        yaml.push_str("    type: chatml\n");
        yaml.push_str(&format!(
            "output_dir: {}\n",
            self.output_dir(&job.id).display()
        ));
        yaml.push_str(&format!("num_epochs: {}\n", p.num_epochs));
        yaml.push_str(&format!("micro_batch_size: {}\n", p.batch_size));
        yaml.push_str(&format!("learning_rate: {:.6}\n", p.learning_rate));
        yaml.push_str("adapter: lora\n");
        yaml.push_str(&format!("lora_r: {}\n", lo.r));
        yaml.push_str(&format!("lora_alpha: {}\n", lo.alpha));
        yaml.push_str(&format!("lora_dropout: {}\n", lo.dropout));
        yaml.push_str("lora_target_modules:\n");
        for m in &lo.target_modules {
            yaml.push_str(&format!("  - {}\n", m));
        }
        if !lo.modules_to_save.is_empty() {
            yaml.push_str("lora_modules_to_save:\n");
            for m in &lo.modules_to_save {
                yaml.push_str(&format!("  - {}\n", m));
            }
        }
        if lo.use_rslora {
            yaml.push_str("use_rslora: true\n");
        }

        // Quantization
        if q.load_in_4bit {
            yaml.push_str("load_in_4bit: true\n");
            if let Some(ref dt) = q.bnb_4bit_compute_dtype {
                yaml.push_str(&format!("bnb_4bit_compute_dtype: {}\n", dt));
            }
            if let Some(ref qt) = q.bnb_4bit_quant_type {
                yaml.push_str(&format!("bnb_4bit_quant_type: {}\n", qt));
            }
            if q.bnb_4bit_use_double_quant {
                yaml.push_str("bnb_4bit_use_double_quant: true\n");
            }
        } else if q.load_in_8bit {
            yaml.push_str("load_in_8bit: true\n");
        }

        // Optimizer & scheduler
        if let Some(ref optimizer) = opt.optimizer {
            yaml.push_str(&format!("optimizer: {}\n", optimizer));
        }
        if opt.weight_decay > 0.0 {
            yaml.push_str(&format!("weight_decay: {}\n", opt.weight_decay));
        }
        if opt.gradient_accumulation_steps > 1 {
            yaml.push_str(&format!(
                "gradient_accumulation_steps: {}\n",
                opt.gradient_accumulation_steps
            ));
        }
        if let Some(ref sched) = opt.lr_scheduler {
            yaml.push_str(&format!("lr_scheduler: {}\n", sched));
        }
        if let Some(ws) = opt.warmup_steps {
            yaml.push_str(&format!("warmup_steps: {}\n", ws));
        } else if let Some(wr) = opt.warmup_ratio {
            yaml.push_str(&format!("warmup_ratio: {}\n", wr));
        }
        if let Some(mgn) = opt.max_grad_norm {
            yaml.push_str(&format!("max_grad_norm: {}\n", mgn));
        }

        // Sequence
        if let Some(sl) = seq.sequence_len {
            yaml.push_str(&format!("sequence_len: {}\n", sl));
        }
        if seq.sample_packing {
            yaml.push_str("sample_packing: true\n");
        }
        if seq.pad_to_sequence_len {
            yaml.push_str("pad_to_sequence_len: true\n");
        }
        if let Some(na) = seq.neftune_noise_alpha {
            yaml.push_str(&format!("neftune_noise_alpha: {}\n", na));
        }

        // Advanced
        if let Some(ref attn) = adv.attn_implementation {
            yaml.push_str(&format!("attn_implementation: {}\n", attn));
        }
        if let Some(ref gc) = adv.gradient_checkpointing {
            yaml.push_str(&format!("gradient_checkpointing: {}\n", gc));
        }
        if adv.bf16 {
            yaml.push_str("bf16: true\n");
        } else if adv.fp16 {
            yaml.push_str("fp16: true\n");
        }
        if let Some(esr) = adv.eval_split_ratio {
            yaml.push_str(&format!("eval_split_ratio: {}\n", esr));
        }

        Ok(yaml)
    }

    fn output_dir(&self, job_id: &str) -> PathBuf {
        PathBuf::from(format!("./axolotl-output/{}", job_id))
    }

    fn completion_marker(&self, job_id: &str) -> PathBuf {
        self.output_dir(job_id).join("adapter_model.safetensors")
    }

    fn harness_id(&self) -> TrainingHarnessId {
        TrainingHarnessId::Axolotl
    }
}

// ── Unsloth harness ────────────────────────────────────────────────────────

/// Renders unsloth Python training script from canonical TrainingParams.
pub struct UnslothHarness;

impl HarnessAdapter for UnslothHarness {
    fn render_config(&self, job: &TrainingJob) -> Result<String, ProviderError> {
        let p = &job.params;
        let lo = &p.lora;
        let q = &p.quantization;
        let opt = &p.optimization;
        let seq = &p.sequence;
        let adv = &p.advanced;

        let target_modules_str = lo
            .target_modules
            .iter()
            .map(|m| format!("\"{}\"", m))
            .collect::<Vec<_>>()
            .join(", ");

        let mut script = String::new();
        script.push_str("# Auto-generated by hKask Training Server (harness: unsloth)\n");
        script.push_str("import torch\n");
        script.push_str("from unsloth import FastLanguageModel\n");
        script.push_str("from datasets import load_dataset\n");
        script.push_str("from transformers import EarlyStoppingCallback\n");
        script.push_str("from trl import SFTTrainer, SFTConfig\n\n");

        // Model loading with quantization
        let load_kwargs = if q.load_in_4bit {
            ", load_in_4bit=True"
        } else {
            ""
        };
        let max_seq = seq.sequence_len.unwrap_or(2048);
        script.push_str(&format!(
            "model, tokenizer = FastLanguageModel.from_pretrained(\n    model_name=\"{}\",\n    max_seq_length={}{}\n)\n\n",
            job.base_model, max_seq, load_kwargs
        ));

        // PEFT config
        let grad_ckpt = adv.gradient_checkpointing.as_deref().unwrap_or("unsloth");
        script.push_str("model = FastLanguageModel.get_peft_model(\n    model,\n");
        script.push_str(&format!("    r={},\n", lo.r));
        script.push_str(&format!("    lora_alpha={},\n", lo.alpha));
        script.push_str(&format!("    target_modules=[{}],\n", target_modules_str));
        script.push_str(&format!("    lora_dropout={},\n", lo.dropout));
        script.push_str("    bias=\"none\",\n");
        script.push_str(&format!(
            "    use_gradient_checkpointing=\"{}\",\n",
            grad_ckpt
        ));
        if lo.use_rslora {
            script.push_str("    use_rslora=True,\n");
        }
        script.push_str(")\n\n");

        // Dataset — load with train/eval split when eval is enabled
        if adv.eval_split_ratio.is_some() {
            script.push_str(&format!(
                "dataset = load_dataset(\"json\", data_files=\"{}\", split=\"train\")\n",
                job.dataset_path.display()
            ));
            script.push_str("split = int(len(dataset) * 0.9)\n");
            script.push_str("train_ds = dataset.select(range(split))\n");
            script.push_str("eval_ds = dataset.select(range(split, len(dataset)))\n\n");
        } else {
            script.push_str(&format!(
                "dataset = load_dataset(\"json\", data_files=\"{}\", split=\"train\")\n\n",
                job.dataset_path.display()
            ));
        }

        // SFTTrainer — use processing_class (not tokenizer=, which is deprecated in TRL >=0.12)
        if adv.eval_split_ratio.is_some() {
            script.push_str("trainer = SFTTrainer(\n    model=model,\n    processing_class=tokenizer,\n    train_dataset=train_ds,\n    eval_dataset=eval_ds,\n    dataset_text_field=\"text\",\n");
        } else {
            script.push_str("trainer = SFTTrainer(\n    model=model,\n    processing_class=tokenizer,\n    train_dataset=dataset,\n    dataset_text_field=\"text\",\n");
        }
        script.push_str(&format!("    max_seq_length={},\n", max_seq));
        script.push_str("    args=SFTConfig(\n");
        script.push_str(&format!(
            "        per_device_train_batch_size={},\n",
            p.batch_size
        ));
        script.push_str(&format!("        num_train_epochs={},\n", p.num_epochs));
        script.push_str(&format!("        learning_rate={},\n", p.learning_rate));
        if let Some(ref sched) = opt.lr_scheduler {
            script.push_str(&format!("        lr_scheduler_type=\"{}\",\n", sched));
        }
        // Warmup: prefer warmup_steps if set, else warmup_ratio
        if let Some(ws) = opt.warmup_steps {
            script.push_str(&format!("        warmup_steps={},\n", ws));
        } else if let Some(wr) = opt.warmup_ratio {
            script.push_str(&format!("        warmup_ratio={},\n", wr));
        }
        if opt.weight_decay > 0.0 {
            script.push_str(&format!("        weight_decay={},\n", opt.weight_decay));
        }
        if let Some(mgn) = opt.max_grad_norm {
            script.push_str(&format!("        max_grad_norm={},\n", mgn));
        }
        if opt.gradient_accumulation_steps > 1 {
            script.push_str(&format!(
                "        gradient_accumulation_steps={},\n",
                opt.gradient_accumulation_steps
            ));
        }
        if adv.bf16 {
            script.push_str("        bf16=True,\n");
        } else if adv.fp16 {
            script.push_str("        fp16=True,\n");
        }
        // Eval + early stopping + save strategy
        if adv.eval_split_ratio.is_some() {
            script.push_str("        eval_strategy=\"steps\",\n");
            script.push_str("        eval_steps=50,\n");
            script.push_str("        load_best_model_at_end=True,\n");
            script.push_str("        metric_for_best_model=\"eval_loss\",\n");
            script.push_str("        greater_is_better=False,\n");
            script.push_str("        save_strategy=\"steps\",\n");
            script.push_str("        save_steps=100,\n");
            script.push_str("        save_total_limit=3,\n");
        }
        script.push_str(&format!(
            "        output_dir=\"{}\",\n",
            self.output_dir(&job.id).display()
        ));
        script.push_str("        report_to=\"none\",\n");
        script.push_str("    ),\n");
        if seq.sample_packing {
            script.push_str("    packing=True,\n");
        }
        if let Some(na) = seq.neftune_noise_alpha {
            script.push_str(&format!("    neftune_noise_alpha={},\n", na));
        }
        // Early stopping callback when eval is enabled
        if adv.eval_split_ratio.is_some() {
            script.push_str("    callbacks=[EarlyStoppingCallback(early_stopping_patience=10)],\n");
        }
        script.push_str(")\n\n");

        script.push_str("trainer.train()\n");
        script.push_str(&format!(
            "model.save_pretrained(\"{}\")\n",
            self.completion_marker(&job.id)
                .parent()
                .expect("completion marker always has a parent directory")
                .display()
        ));

        Ok(script)
    }

    fn output_dir(&self, job_id: &str) -> PathBuf {
        PathBuf::from(format!("./unsloth-output/{}", job_id))
    }

    fn completion_marker(&self, job_id: &str) -> PathBuf {
        self.output_dir(job_id)
            .join("adapter")
            .join("adapter_model.safetensors")
    }

    fn harness_id(&self) -> TrainingHarnessId {
        TrainingHarnessId::Unsloth
    }
}

// ── Tinker harness ────────────────────────────────────────────────────────

/// Renders a Tinker Python training script from canonical `TrainingParams`.
///
/// Unlike Axolotl (YAML) and Unsloth (Python using HF transformers), Tinker
/// renders a Python script that uses the `tinker` SDK to drive the training
/// loop: `ServiceClient` then `create_lora_training_client` then
/// `forward_backward` then `optim_step` then
/// `save_weights_and_get_sampling_client`. The script runs on the host CPU;
/// Tinker's service handles distributed GPU compute.
///
/// The Tinker host (`TinkerHost`) writes this script to a temp file and
/// launches it as a `python3` subprocess. The script is an ad-hoc artifact —
/// it is generated per job and not committed to the repository.
pub struct TinkerHarness;

impl HarnessAdapter for TinkerHarness {
    fn render_config(&self, job: &TrainingJob) -> Result<String, ProviderError> {
        let p = &job.params;
        let lo = &p.lora;
        let opt = &p.optimization;
        let seq = &p.sequence;
        let adv = &p.advanced;

        let max_seq = seq.sequence_len.unwrap_or(2048) as usize;
        let grad_accum = opt.gradient_accumulation_steps.max(1);
        let checkpoint_every = 100u32;
        let eval_steps = adv.eval_split_ratio.map(|_| 50u32);

        let mut script = String::new();
        script.push_str("# Auto-generated by hKask Training Server (harness: tinker)\n");
        script.push_str("# Tinker SDK: https://tinker-docs.thinkingmachines.ai/tinker/\n");
        script.push_str("# Reads TINKER_API_KEY from the environment.\n");
        script.push_str("import asyncio\n");
        script.push_str("import json\n");
        script.push_str("import os\n");
        script.push_str("import sys\n");
        script.push('\n');
        script.push_str("import tinker\n");
        script.push_str("from tinker import types\n");
        script.push('\n');
        script.push_str("# hKask job metadata (injected by TinkerHost)\n");
        script.push_str(&format!(
            "JOB_ID = os.environ.get(\"HKASK_JOB_ID\", \"{}\")\n",
            job.id
        ));
        script.push_str(&format!(
            "DATASET_PATH = os.environ.get(\"HKASK_DATASET_PATH\", \"{}\")\n",
            job.dataset_path.display().to_string().replace('"', "\\\"")
        ));
        script.push_str(&format!(
            "BASE_MODEL = os.environ.get(\"HKASK_BASE_MODEL\", \"{}\")\n",
            job.base_model.replace('"', "\\\"")
        ));
        script.push_str(&format!("LORA_RANK = {}\n", lo.r));
        script.push_str(&format!("NUM_EPOCHS = {}\n", p.num_epochs));
        script.push_str(&format!("BATCH_SIZE = {}\n", p.batch_size));
        script.push_str(&format!("GRAD_ACCUM = {}\n", grad_accum));
        script.push_str(&format!("LEARNING_RATE = {:.8e}\n", p.learning_rate));
        script.push_str(&format!("MAX_SEQ_LEN = {}\n", max_seq));
        script.push_str(&format!("CHECKPOINT_EVERY = {}\n", checkpoint_every));
        script.push_str(&format!(
            "OUTPUT_DIR = os.environ.get(\"HKASK_TINKER_OUTPUT_DIR\", \"{}\")\n",
            self.output_dir(&job.id).display().to_string().replace('"', "\\\"")
        ));
        script.push_str(&format!(
            "LOG_PATH = os.environ.get(\"HKASK_TINKER_LOG_PATH\", \"{}\")\n",
            self.output_dir(&job.id)
                .join("tinker.log")
                .display()
                .to_string()
                .replace('"', "\\\"")
        ));
        if let Some(es) = eval_steps {
            script.push_str(&format!("EVAL_STEPS = {}\n", es));
        } else {
            script.push_str("EVAL_STEPS = None\n");
        }
        script.push('\n');
        script.push_str("os.makedirs(OUTPUT_DIR, exist_ok=True)\n");
        script.push('\n');
        script.push('\n');
        script.push_str("def log(line):\n");
        script.push_str("    msg = f\"[tinker] {line}\"\n");
        script.push_str("    print(msg, flush=True)\n");
        script.push_str("    with open(LOG_PATH, \"a\", encoding=\"utf-8\") as fh:\n");
        script.push_str("        fh.write(msg + \"\\n\")\n");
        script.push('\n');
        script.push('\n');
        // Dataset loading: ChatML JSONL → tokenized Datum objects
        script.push_str("def load_dataset_examples(tokenizer, path):\n");
        script.push_str("    examples = []\n");
        script.push_str("    with open(path, \"r\", encoding=\"utf-8\") as fh:\n");
        script.push_str("        for line in fh:\n");
        script.push_str("            line = line.strip()\n");
        script.push_str("            if not line:\n");
        script.push_str("                continue\n");
        script.push_str("            row = json.loads(line)\n");
        script.push_str("            messages = row.get(\"messages\", [])\n");
        script.push_str("            if not messages:\n");
        script.push_str("                continue\n");
        script.push_str("            text = tokenizer.apply_chat_template(\n");
        script.push_str("                messages, tokenize=False, add_generation_prompt=False\n");
        script.push_str("            )\n");
        script.push_str("            tokens = tokenizer.encode(text, add_special_tokens=False)\n");
        script.push_str("            tokens = tokens[:MAX_SEQ_LEN]\n");
        script.push_str("            if len(tokens) < 2:\n");
        script.push_str("                continue\n");
        script.push_str("            input_tokens = tokens[:-1]\n");
        script.push_str("            target_tokens = tokens[1:]\n");
        script.push_str("            weights = [1.0] * len(target_tokens)\n");
        script.push_str("            datum = types.Datum(\n");
        script.push_str("                model_input=types.ModelInput.from_ints(tokens=input_tokens),\n");
        script.push_str("                loss_fn_inputs=dict(\n");
        script.push_str("                    weights=weights,\n");
        script.push_str("                    target_tokens=target_tokens,\n");
        script.push_str("                ),\n");
        script.push_str("            )\n");
        script.push_str("            examples.append(datum)\n");
        script.push_str("    return examples\n");
        script.push('\n');
        script.push('\n');
        // Main training loop
        script.push_str("async def main():\n");
        script.push_str("    log(f\"job={JOB_ID} base_model={BASE_MODEL} rank={LORA_RANK} epochs={NUM_EPOCHS}\")\n");
        script.push_str("    service_client = tinker.ServiceClient()\n");
        script.push_str("    log(\"service client created\")\n");
        script.push_str("    training_client = service_client.create_lora_training_client(\n");
        script.push_str("        base_model=BASE_MODEL, rank=LORA_RANK\n");
        script.push_str("    )\n");
        script.push_str("    log(\"lora training client created\")\n");
        script.push_str("    tokenizer = training_client.get_tokenizer()\n");
        script.push_str("    examples = load_dataset_examples(tokenizer, DATASET_PATH)\n");
        script.push_str("    log(f\"loaded {len(examples)} training examples\")\n");
        script.push_str("    if not examples:\n");
        script.push_str("        log(\"ERROR: no training examples\")\n");
        script.push_str("        sys.exit(1)\n");
        script.push('\n');
        script.push_str("    eval_examples = []\n");
        script.push_str("    if EVAL_STEPS is not None:\n");
        script.push_str("        split = max(1, int(len(examples) * 0.9))\n");
        script.push_str("        eval_examples = examples[split:]\n");
        script.push_str("        examples = examples[:split]\n");
        script.push_str("        log(f\"train={len(examples)} eval={len(eval_examples)}\")\n");
        script.push('\n');
        script.push_str("    adam_params = types.AdamParams(learning_rate=LEARNING_RATE)\n");
        script.push_str("    step = 0\n");
        script.push_str("    for epoch in range(NUM_EPOCHS):\n");
        script.push_str("        for i in range(0, len(examples), BATCH_SIZE * GRAD_ACCUM):\n");
        script.push_str("            batch = examples[i : i + BATCH_SIZE]\n");
        script.push_str("            if not batch:\n");
        script.push_str("                continue\n");
        script.push_str("            fwdbwd_future = await training_client.forward_backward_async(\n");
        script.push_str("                data=batch, loss_fn=\"cross_entropy\"\n");
        script.push_str("            )\n");
        script.push_str("            fwdbwd_result = await fwdbwd_future.result_async()\n");
        script.push_str("            loss = float(getattr(fwdbwd_result, \"loss\", float(\"nan\")))\n");
        script.push_str("            if ((step + 1) % GRAD_ACCUM) == 0:\n");
        script.push_str("                optim_future = await training_client.optim_step_async(adam_params)\n");
        script.push_str("                await optim_future.result_async()\n");
        script.push_str("            step += 1\n");
        script.push_str("            if step % 10 == 0:\n");
        script.push_str("                log(f\"step={step} epoch={epoch} loss={loss:.6}\")\n");
        script.push_str("            if step % CHECKPOINT_EVERY == 0:\n");
        script.push_str("                ckpt_name = f\"{JOB_ID}-step-{step}\"\n");
        script.push_str("                training_client.save_state(name=ckpt_name)\n");
        script.push_str("                log(f\"checkpoint saved name={ckpt_name}\")\n");
        script.push_str("            if EVAL_STEPS is not None and eval_examples and step % EVAL_STEPS == 0:\n");
        script.push_str("                eval_future = await training_client.forward_backward_async(\n");
        script.push_str("                    data=eval_examples, loss_fn=\"cross_entropy\"\n");
        script.push_str("                )\n");
        script.push_str("                eval_result = await eval_future.result_async()\n");
        script.push_str("                eval_loss = float(getattr(eval_result, \"loss\", float(\"nan\")))\n");
        script.push_str("                log(f\"step={step} eval_loss={eval_loss:.6}\")\n");
        script.push_str("    if step % GRAD_ACCUM != 0:\n");
        script.push_str("        optim_future = await training_client.optim_step_async(adam_params)\n");
        script.push_str("        await optim_future.result_async()\n");
        script.push('\n');
        script.push_str("    final_name = f\"{JOB_ID}-final\"\n");
        script.push_str("    sampling_client = training_client.save_weights_and_get_sampling_client(\n");
        script.push_str("        name=final_name\n");
        script.push_str("    )\n");
        script.push_str("    log(f\"final weights saved name={final_name}\")\n");
        script.push('\n');
        script.push_str("    training_client.save_state(name=f\"{JOB_ID}-state\")\n");
        script.push('\n');
        script.push_str("    marker = os.path.join(OUTPUT_DIR, \"tinker_complete.json\")\n");
        script.push_str("    with open(marker, \"w\", encoding=\"utf-8\") as fh:\n");
        script.push_str("        json.dump({\n");
        script.push_str("            \"job_id\": JOB_ID,\n");
        script.push_str("            \"base_model\": BASE_MODEL,\n");
        script.push_str("            \"output_name\": final_name,\n");
        script.push_str("            \"checkpoint_name\": f\"{JOB_ID}-state\",\n");
        script.push_str("            \"steps\": step,\n");
        script.push_str("            \"epochs\": NUM_EPOCHS,\n");
        script.push_str("        }, fh)\n");
        script.push_str("    log(f\"completion marker written path={marker}\")\n");
        script.push('\n');
        script.push('\n');
        script.push_str("if __name__ == \"__main__\":\n");
        script.push_str("    asyncio.run(main())\n");

        Ok(script)
    }

    fn output_dir(&self, job_id: &str) -> PathBuf {
        PathBuf::from(format!("./tinker-output/{}", job_id))
    }

    fn completion_marker(&self, job_id: &str) -> PathBuf {
        self.output_dir(job_id).join("tinker_complete.json")
    }

    fn harness_id(&self) -> TrainingHarnessId {
        TrainingHarnessId::Tinker
    }
}
