//! Kata↔Kanban integration executor.
//!
//! `KanbanKataBridge` executes full kata cycles on kanban tasks by adapting
//! task state into `KataState` and delegating to `KataEngine`. This replaces
//! the old `kanban_impl/kata.rs` inline prompt generator with a complete
//! execution pipeline that emits CNS spans, tracks gas, and computes
//! automaticity through the engine.

use std::collections::HashMap;
use std::sync::Arc;

use crate::kanban::Task;
use crate::kata::{KataEngine, KataError, KataManifest, KataResult};

/// Executes kata cycles on kanban tasks. Not a prompt generator — a full
/// execution orchestrator that delegates to KataEngine for inference, CNS
/// span emission, gas tracking, and automaticity.
pub(crate) struct KanbanKataBridge {
    engine: Arc<KataEngine>,
}

impl KanbanKataBridge {
    pub fn new(engine: Arc<KataEngine>) -> Self {
        Self { engine }
    }

    /// Run a full 5-question Coaching Kata cycle on a task.
    ///
    /// Builds a context from the task's title, description, criteria,
    /// comments, and deliverables. Delegates to `KataEngine::execute()`
    /// with kata_type "coaching". Returns KataResult with CNS spans,
    /// gas tracking, and step experiences — all generated by the engine.
    pub async fn run_coaching_on_task(
        &self,
        task: &Task,
        manifest: &KataManifest,
    ) -> Result<KataResult, KataError> {
        let learner_bot = task_learner_bot(task);
        let context = build_task_context(task);
        self.engine.execute(manifest, &learner_bot, context).await
    }

    /// Run a full 4-step PDCA Improvement Kata cycle on a task.
    ///
    /// Uses task description as the direction, task state + deliverables
    /// as the current condition. Delegates to `KataEngine::execute()`
    /// with kata_type "improvement".
    pub async fn run_improvement_on_task(
        &self,
        task: &Task,
        manifest: &KataManifest,
    ) -> Result<KataResult, KataError> {
        let learner_bot = task_learner_bot(task);
        let context = build_task_context(task);
        self.engine.execute(manifest, &learner_bot, context).await
    }

    /// Run a Starter Kata observation drill on a task sub-problem.
    ///
    /// Delegates to `KataEngine::execute()` with kata_type "starter".
    /// The sub_problem is included in the context for the observation drill.
    pub async fn run_starter_on_task(
        &self,
        task: &Task,
        sub_problem: &str,
        manifest: &KataManifest,
    ) -> Result<KataResult, KataError> {
        let learner_bot = task_learner_bot(task);
        let mut context = build_task_context(task);
        context.insert("sub_problem".to_string(), sub_problem.to_string());
        self.engine.execute(manifest, &learner_bot, context).await
    }
}

/// Resolve the learner identity from a task's assignee or owner.
fn task_learner_bot(task: &Task) -> String {
    task.assignee
        .map(|a| a.to_string())
        .unwrap_or_else(|| task.owner.to_string())
}

/// Build a kata context map from task metadata.
///
/// Maps task fields into the string-keyed context that KataEngine expects.
/// This is the adaptation layer: Task (kanban domain) → context HashMap (kata domain).
fn build_task_context(task: &Task) -> HashMap<String, String> {
    let mut ctx = HashMap::new();
    ctx.insert("task_title".to_string(), task.title.clone());
    if let Some(ref desc) = task.description {
        ctx.insert("task_description".to_string(), desc.clone());
    }
    ctx.insert("task_status".to_string(), task.status.to_string());
    ctx.insert(
        "deliverables_count".to_string(),
        task.deliverables.len().to_string(),
    );
    ctx.insert(
        "comments_count".to_string(),
        task.comments.len().to_string(),
    );
    ctx.insert(
        "criteria_count".to_string(),
        task.criteria.len().to_string(),
    );

    // Include criteria as numbered entries
    for (i, c) in task.criteria.iter().enumerate() {
        ctx.insert(format!("criterion_{}", i + 1), c.description.clone());
    }

    // Include recent comments (last 3)
    for (i, c) in task.comments.iter().rev().take(3).enumerate() {
        ctx.insert(format!("comment_{}", i + 1), c.body.clone());
    }

    // Include deliverables
    for (i, d) in task.deliverables.iter().enumerate() {
        ctx.insert(format!("deliverable_{}", i + 1), d.clone());
    }

    ctx
}
