//! hKask Media MCP Server — Integration Tests
//!
//! Vertical tracer-bullet tests per tool family. Since MCP tool methods are private
//! (generated by `#[tool]` macro), these tests exercise the public component APIs:
//! - GalleryStore + GalleryState: filesystem scan → SQLite persistence → lookup → search
//! - Collage composition: image loading → grid layout → canvas composition → output
//!
//! Tool families NOT covered (require inference, deferred to Option B):
//! - Tagging (vision LLM), Abstraction (vision LLM), Derivation (fal.ai),
//!   Voice (LLM+TTS), Generation (fal.ai), Video (ffmpeg-dependent)

use hkask_mcp_media::gallery::{GalleryMode, GalleryState};
use hkask_storage::gallery::GalleryStore;
use image::{Rgb, RgbImage};
use std::path::PathBuf;
use std::sync::{Arc, Mutex};
use tempfile::TempDir;

// ── Test helpers ──────────────────────────────────────────────────────────

fn setup_store() -> (Arc<GalleryStore>, TempDir) {
    let temp = TempDir::new().expect("tempdir");
    let conn = rusqlite::Connection::open_in_memory().expect("in-memory db");
    let conn = Arc::new(Mutex::new(conn));
    GalleryStore::init_tables(&conn.lock().unwrap()).expect("init tables");
    (Arc::new(GalleryStore::new(conn)), temp)
}

fn create_test_image(dir: &std::path::Path, name: &str, r: u8, g: u8, b: u8) -> PathBuf {
    let img: RgbImage = RgbImage::from_pixel(64, 64, Rgb([r, g, b]));
    let path = dir.join(name);
    img.save(&path).expect("save test image");
    path
}

// ── Gallery lifecycle test ────────────────────────────────────────────────

/// REQ: media-gallery-lifecycle-01 — full gallery lifecycle from init through search.
///
/// Verifies: GalleryStore.create → GalleryState.scan → GalleryStore.get_image →
/// tag_image → get_tags → fuzzy tag search (via GalleryStore.get_all_tags + Levenshtein).
#[test]
fn gallery_lifecycle_init_to_search() {
    let (store, temp) = setup_store();

    // Create test images
    create_test_image(temp.path(), "sunset.jpg", 255, 100, 50);
    create_test_image(temp.path(), "ocean.jpg", 50, 100, 255);
    create_test_image(temp.path(), "forest.png", 34, 139, 34);

    // Step 1: Create gallery record in SQLite
    let gallery = store
        .create(
            &temp.path().to_string_lossy(),
            hkask_storage::GalleryMode::ReadOnly,
        )
        .expect("create gallery");
    assert_eq!(gallery.image_count, 0, "fresh gallery has 0 images");

    // Step 2: Scan directory — GalleryState discovers images
    let mut state = GalleryState::new(temp.path().to_path_buf(), GalleryMode::Original);
    let scan = state.scan(false, None);
    assert_eq!(scan.added, 3, "scan should find 3 images");
    assert_eq!(scan.entries.len(), 3, "scan should return 3 entries");

    // Step 3: Persist discovered images to SQLite
    for entry in &scan.entries {
        store
            .add_image(
                &gallery.id,
                &entry.relative_path,
                &temp.path().join(&entry.relative_path).to_string_lossy(),
                &entry.checksum,
                entry.width,
                entry.height,
                &entry.format,
                entry.size_bytes,
            )
            .expect("add image");
    }

    // Step 4: Retrieve image by index
    let img = store
        .get_image(&gallery.id, Some(0), None)
        .expect("get image by index");
    assert_eq!(img.width, 64, "image width");
    assert_eq!(img.height, 64, "image height");

    // Step 5: Tag images (bypasses inference — direct store access)
    store
        .tag_image(&img.id, "object", "sunset", 0.95, "test")
        .expect("tag sunset");
    store
        .tag_image(&img.id, "color", "orange", 0.9, "test")
        .expect("tag orange");

    let img1 = store
        .get_image(&gallery.id, Some(1), None)
        .expect("get image 1");
    store
        .tag_image(&img1.id, "object", "ocean", 0.95, "test")
        .expect("tag ocean");

    // Step 6: Verify tags (order is by created_at DESC, so don't assume position)
    let tags = store.get_tags(&img.id).expect("get tags");
    assert_eq!(tags.len(), 2, "image should have 2 tags");
    let tag_values: Vec<&str> = tags.iter().map(|t| t.value.as_str()).collect();
    assert!(tag_values.contains(&"sunset"), "should have sunset tag");
    assert!(tag_values.contains(&"orange"), "should have orange tag");

    // Step 7: Search by tag — using the same Levenshtein logic as gallery_search tool
    let all_tags = store.get_all_tags(&gallery.id).expect("get all tags");
    assert!(!all_tags.is_empty(), "should have tags to search");

    // Verify sunset tag is present
    let has_sunset = all_tags.iter().any(|(tag, _)| tag.value == "sunset");
    assert!(has_sunset, "sunset tag should be present");
}

// ── Collage composition test ──────────────────────────────────────────────

/// REQ: media-collage-compose-01 — grid collage composition from programmatic images.
///
/// Verifies the composition algorithm: load images → compute grid → resize →
/// overlay on canvas → save valid PNG output. This is the same logic used by
/// the image_create_collage MCP tool.
#[test]
fn collage_compose_grid_layout() {
    let temp = TempDir::new().expect("tempdir");

    // Create 4 test images with distinct colors
    let red = RgbImage::from_pixel(64, 64, Rgb([255u8, 0, 0]));
    let green = RgbImage::from_pixel(64, 64, Rgb([0, 255u8, 0]));
    let blue = RgbImage::from_pixel(64, 64, Rgb([0, 0, 255u8]));
    let yellow = RgbImage::from_pixel(64, 64, Rgb([255u8, 255u8, 0]));

    // Load as DynamicImage (same as image_create_collage does)
    let images: Vec<image::DynamicImage> = vec![
        image::DynamicImage::ImageRgb8(red),
        image::DynamicImage::ImageRgb8(green),
        image::DynamicImage::ImageRgb8(blue),
        image::DynamicImage::ImageRgb8(yellow),
    ];

    // ── Replicate collage composition algorithm ──

    let spacing: u32 = 8;
    let canvas_w: u32 = 800;
    let canvas_h: u32 = 600;
    let cols = (images.len() as f64).sqrt().ceil() as u32; // grid layout
    let rows = (images.len() as u32 + cols - 1) / cols;

    assert_eq!(cols, 2, "4 images → 2×2 grid");
    assert_eq!(rows, 2, "4 images → 2 rows");

    let cell_w = (canvas_w - spacing * (cols + 1)) / cols;
    let cell_h = (canvas_h - spacing * (rows + 1)) / rows;

    // Create canvas
    let mut canvas = image::DynamicImage::new_rgba8(canvas_w, canvas_h);
    let bg = image::Rgba([30u8, 30u8, 30u8, 255u8]);
    for pixel in canvas.as_mut_rgba8().unwrap().pixels_mut() {
        *pixel = bg;
    }

    // Place images
    for (i, img) in images.iter().enumerate() {
        let col = i as u32 % cols;
        let row = i as u32 / cols;

        let scaled = img.resize_exact(
            cell_w.saturating_sub(spacing),
            cell_h.saturating_sub(spacing),
            image::imageops::FilterType::Lanczos3,
        );

        let x = spacing
            + col * (cell_w + spacing)
            + (cell_w.saturating_sub(spacing) - scaled.width()) / 2;
        let y = spacing
            + row * (cell_h + spacing)
            + (cell_h.saturating_sub(spacing) - scaled.height()) / 2;

        image::imageops::overlay(&mut canvas, &scaled, x as i64, y as i64);
    }

    // Save and verify
    let output_path = temp.path().join("collage_test.png");
    canvas.save(&output_path).expect("save collage");

    let collage = image::open(&output_path).expect("reopen collage");
    assert_eq!(collage.width(), 800, "output width");
    assert_eq!(collage.height(), 600, "output height");

    // Verify the output is not just the background (should have non-background pixels)
    let rgba = collage.to_rgba8();
    let non_bg = rgba.pixels().filter(|p| p.0 != [30, 30, 30, 255]).count();
    assert!(
        non_bg > 100,
        "collage should have non-background pixels (got {})",
        non_bg
    );
}

// ── Gallery error paths test ──────────────────────────────────────────────

/// REQ: media-gallery-error-01 — gallery store returns clear errors for invalid lookups.
///
/// Verifies: get_image with out-of-range index returns ImageNotFound error.
#[test]
fn gallery_store_image_not_found() {
    let (store, temp) = setup_store();

    let gallery = store
        .create(
            &temp.path().to_string_lossy(),
            hkask_storage::GalleryMode::ReadOnly,
        )
        .expect("create gallery");

    // Lookup with non-existent index
    let result = store.get_image(&gallery.id, Some(999), None);
    assert!(result.is_err(), "out-of-range index should error");
    let err = result.unwrap_err().to_string();
    assert!(
        err.contains("index=999") || err.contains("not found"),
        "error should mention missing index: {}",
        err
    );

    // Lookup with non-existent hash
    let result = store.get_image(&gallery.id, None, Some("nonexistent"));
    assert!(result.is_err(), "non-existent hash should error");
}

// ── Gallery three-state policy test ───────────────────────────────────────

/// REQ: media-gallery-policy-01 — three gallery modes are distinct.
///
/// Verifies: ReadOnly, CopyOnWrite, Destructive have different as_str values
/// and GalleryState validates paths correctly for each mode.
#[test]
fn gallery_three_state_policy() {
    use hkask_storage::GalleryMode as StorageGalleryMode;

    assert_eq!(StorageGalleryMode::ReadOnly.as_str(), "read-only");
    assert_eq!(StorageGalleryMode::CopyOnWrite.as_str(), "copy-on-write");
    assert_eq!(StorageGalleryMode::Destructive.as_str(), "destructive");
    assert_ne!(
        StorageGalleryMode::ReadOnly.as_str(),
        StorageGalleryMode::Destructive.as_str()
    );

    // GalleryState rejects non-existent paths
    let result = GalleryState::new(
        std::path::PathBuf::from("/nonexistent/path/12345"),
        GalleryMode::Original,
    );
    assert!(result.validate().is_err(), "should reject missing path");
}
