//! CLI markdown documentation generator

/// Generate the CLI help documentation as markdown.
///
/// Emits the mandatory documentation metadata header (per
/// `docs/specifications/DOCUMENTATION_STANDARDS.md` §2) so the generated file
/// passes `docs/ci/check-metadata.sh` without hand-editing.
///
/// expect: "I can access all hKask functionality through the kask CLI"
/// pre:  none
/// post: returns a String containing full CLI markdown documentation with metadata header
pub fn generate_cli_markdown() -> String {
    let mut md = String::new();

    md.push_str("---\n");
    md.push_str("title: \"hKask CLI Reference (auto-generated)\"\n");
    md.push_str("audience: [CLI operators, developers, agents]\n");
    md.push_str("last_updated: 2026-06-12\n");
    md.push_str(&format!("version: \"{}\"\n", env!("CARGO_PKG_VERSION")));
    md.push_str("status: \"Active\"\n");
    md.push_str("domain: \"Cross-cutting\"\n");
    md.push_str("mds_categories: [interface]\n");
    md.push_str("---\n\n");
    md.push_str("<!-- Generated by `kask docs cli`. Do not hand-edit. -->\n\n");

    md.push_str("# hKask CLI Documentation\n\n");
    md.push_str(
        "**hKask** (ℏKask - \"A Minimal Viable Container for Replicants\") - Command-line interface\n\n",
    );
    md.push_str("## Usage\n\n");
    md.push_str("```bash\n");
    md.push_str("kask [OPTIONS] <COMMAND>\n");
    md.push_str("```\n\n");
    md.push_str("## Options\n\n");
    md.push_str("- `-v`, `--verbose` — Enable verbose output\n");
    md.push_str("- `-r`, `--registry <PATH>` — Registry database path (default: in-memory)\n");
    md.push_str("- `-h`, `--help` — Print help\n");
    md.push_str("- `-V`, `--version` — Print version\n\n");
    md.push_str("## Commands\n\n");
    md.push_str("### `kask chat` — Interactive agent chat\n\n");
    md.push_str("```bash\n");
    md.push_str("kask chat [AGENT]             # Default: Curator\n");
    md.push_str("kask chat -m qwen3:8b        # Start with specific model\n");
    md.push_str("kask chat -f input.txt        # Non-interactive (file input)\n");
    md.push_str("echo \"hello\" | kask chat -f - -m qwen3:8b  # Pipe with model\n");
    md.push_str("```\n\n");
    md.push_str("Arguments:\n");
    md.push_str("- `[AGENT]` — Agent to chat with (default: Curator)\n\n");
    md.push_str("Options:\n");
    md.push_str("- `-t`, `--template <TEMPLATE>` — Template ID to use\n");
    md.push_str(
        "- `-m`, `--model <MODEL>` — Model for inference (e.g., \"DI/google/gemma-4-9b-it\")\n",
    );
    md.push_str("- `-f`, `--input <INPUT>` — Input file (non-interactive mode)\n\n");
    md.push_str("Slash commands (inside chat):\n");
    md.push_str("- `/help` — Show categorized help, `/help <cmd>` for details\n");
    md.push_str("- `/status` — System status (CNS, agent, model, pods)\n");
    md.push_str("- `/agent [NAME]` — Show or switch agent\n");
    md.push_str("- `/agents` — List registered agents\n");
    md.push_str("- `/model` — Show current model\n");
    md.push_str("- `/model list` — List all available models\n");
    md.push_str(
        "- `/model <name>` — Switch to a specific model (e.g., `/model deepseek-v4-pro`)\n",
    );
    md.push_str("- `/model <query>` — Fuzzy search models (e.g., `/model deepseek` lists all DeepSeek models)\n");
    md.push_str(
        "- Set `HKASK_FUSION_JUDGE` + `HKASK_FUSION_PANEL` to customize fusion (see .env.example)\n",
    );
    md.push_str("- `/pods` — List agent pods\n");
    md.push_str("- `/templates` — List registered templates\n");
    md.push_str("- `/escalations` — List pending escalations\n");
    md.push_str("- `/metacognition` — Run metacognition cycle\n");
    md.push_str("- `/sovereignty` — Show sovereignty status\n");
    md.push_str("- `/history` — Show session turn history\n");
    md.push_str("- `/quit` — End session\n\n");
    md.push_str("### `kask template` — Template management\n\n");
    md.push_str("```bash\n");
    md.push_str("kask template <SUBCOMMAND>\n");
    md.push_str("```\n\n");
    md.push_str("Subcommands:\n");
    md.push_str("- `list` — List all registered templates\n");
    md.push_str("  - `-t`, `--type <TYPE>` — Filter by template type\n");
    md.push_str("- `register` — Register a new template\n");
    md.push_str("  - `-i`, `--id <ID>` — Template ID (e.g., \"prompt/selector\")\n");
    md.push_str("  - `-p`, `--path <PATH>` — Template file path\n");
    md.push_str("  - `-t`, `--type <TYPE>` — Template type (prompt, cognition, process)\n");
    md.push_str("  - `-l`, `--lexicon <LEXICON>` — Lexicon terms (comma-separated)\n");
    md.push_str("  - `-d`, `--description <DESC>` — Description\n");
    md.push_str("- `get <ID>` — Get template details\n");
    md.push_str("- `search <TERM>` — Search templates by lexicon term\n\n");
    md.push_str("### `kask bot` — Bot capability management\n\n");
    md.push_str("```bash\n");
    md.push_str("kask bot <SUBCOMMAND>\n");
    md.push_str("```\n\n");
    md.push_str("Subcommands:\n");
    md.push_str("- `list` — List bot capabilities\n");
    md.push_str("  - `-b`, `--bot-id <BOT_ID>` — Bot WebID\n\n");
    md.push_str("### `kask pod` — Agent pod management\n\n");
    md.push_str("```bash\n");
    md.push_str("kask pod <SUBCOMMAND>\n");
    md.push_str("```\n\n");
    md.push_str("Subcommands:\n");
    md.push_str("- `create` — Create agent pod from template crate\n");
    md.push_str("  - `-t`, `--template <TEMPLATE>` — Template crate name\n");
    md.push_str("  - `-p`, `--persona <PERSONA>` — Agent persona YAML file path\n");
    md.push_str("  - `-n`, `--name <NAME>` — Pod name (optional, defaults to UUID)\n");
    md.push_str("- `activate <POD_ID>` — Activate agent pod for A2A communication\n");
    md.push_str("- `deactivate <POD_ID>` — Deactivate agent pod\n");
    md.push_str("- `status <POD_ID>` — Show agent pod status\n");
    md.push_str("  - `-v`, `--verbose` — Show verbose details\n");
    md.push_str("- `list` — List all agent pods\n\n");
    md.push_str("### `kask mcp` — MCP server/tool management\n\n");
    md.push_str("```bash\n");
    md.push_str("kask mcp <SUBCOMMAND>\n");
    md.push_str("```\n\n");
    md.push_str("Subcommands:\n");
    md.push_str("- `list-servers` — List MCP servers\n");
    md.push_str("- `list-tools` — List available tools\n");
    md.push_str("- `get-tool <NAME>` — Get tool definition\n\n");
    md.push_str("### `kask cns` — CNS monitoring\n\n");
    md.push_str("```bash\n");
    md.push_str("kask cns <SUBCOMMAND>\n");
    md.push_str("```\n\n");
    md.push_str("Subcommands:\n");
    md.push_str("- `health` — Get CNS health status\n");
    md.push_str("- `alerts` — Get algedonic alerts\n");
    md.push_str("- `variety` — Get variety counters\n\n");
    md.push_str("### `kask goal` — Goal coordination substrate (OCAP-gated, CNS-observed)\n\n");
    md.push_str("```bash\n");
    md.push_str("kask goal <SUBCOMMAND>\n");
    md.push_str("```\n\n");
    md.push_str("Subcommands:\n");
    md.push_str("- `create <TEXT> [--visibility private|public]` — Create a goal you own\n");
    md.push_str("- `list [--state <STATE>]` — List your goals\n");
    md.push_str("- `set-state <ID> <STATE>` — Transition a goal (legal transitions only)\n\n");
    md.push_str("### `kask docs` — Documentation generation\n\n");
    md.push_str("```bash\n");
    md.push_str("kask docs <SUBCOMMAND>\n");
    md.push_str("```\n\n");
    md.push_str("Subcommands:\n");
    md.push_str("- `openapi` — Generate OpenAPI specification (JSON)\n");
    md.push_str("  - `-o`, `--output <OUTPUT>` — Output file path (default: stdout)\n");
    md.push_str("- `cli` — Generate CLI help documentation (markdown)\n");
    md.push_str("  - `-o`, `--output <OUTPUT>` — Output file path (default: stdout)\n");
    md.push_str("- `all` — Generate all documentation\n");
    md.push_str("  - `-o`, `--output <OUTPUT>` — Output directory\n\n");
    md.push_str("## Examples\n\n");
    md.push_str("```bash\n");
    md.push_str("# Start chat session\n");
    md.push_str("kask chat\n\n");
    md.push_str("# Chat with model selection\n");
    md.push_str("kask chat -m qwen3:8b\n\n");
    md.push_str("# Non-interactive with model\n");
    md.push_str("echo \"Summarize this\" | kask chat -f - -m qwen3:8b\n\n");
    md.push_str("# Inside chat: switch models\n");
    md.push_str("/model              # Show current model\n");
    md.push_str("/model list         # List all available models\n");
    md.push_str("/model qwen         # Fuzzy search for Qwen models\n");
    md.push_str("/model qwen3:8b     # Switch to qwen3:8b\n\n");
    md.push_str("# List all templates\n");
    md.push_str("kask template list\n\n");
    md.push_str("# Register a new template\n");
    md.push_str("kask template register -i prompt/selector -p templates/selector.j2 -t prompt -l \"select,route,dispatch\"\n\n");
    md.push_str("# Generate OpenAPI spec\n");
    md.push_str("kask docs openapi -o docs/openapi.json\n\n");
    md.push_str("# Generate all documentation\n");
    md.push_str("kask docs all -o docs/\n");
    md.push_str("```\n\n");
    md.push_str("## Template Types\n\n");
    md.push_str("- `prompt` — Prompt templates for LLM interaction\n");
    md.push_str("- `cognition` — Cognitive processing templates\n");
    md.push_str("- `process` — Process execution templates\n\n");
    md.push_str("---\n\n");
    md.push_str(&format!(
        "*ℏKask v{} - A Minimal Viable Container for Replicants*\n",
        env!("CARGO_PKG_VERSION")
    ));

    md
}
