apiVersion: v1
kind: ConfigMap
metadata:
  name: hkask-config
  namespace: hkask
data:
  domain: "hkask.example.com"
  conduit-server-name: "hkask.example.com"
  litestream-bucket: "hkask-backups"
  litestream-endpoint: "https://s3.example.com"
  litestream-region: "auto"
  litestream-force-path-style: "true"
  litestream.yml: |
    dbs:
      - path: /data/kask.db
        replicas:
          - type: s3
            bucket: $LITESTREAM_BUCKET
            path: kask
            endpoint: $LITESTREAM_ENDPOINT
            region: $LITESTREAM_REGION
            access-key-id: $LITESTREAM_ACCESS_KEY_ID
            secret-access-key: $LITESTREAM_SECRET_ACCESS_KEY
            force-path-style: true
