apiVersion: v1
kind: Service
metadata:
  name: hkask
  namespace: hkask
  labels:
    app: hkask
spec:
  selector:
    app: hkask
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      protocol: TCP
