//! Skill loader — discovers, parses, and registers SKILL.md files from both zones
//
//! Two-zone model (src→dist pattern):
//! - **Private zone** (`.agents/skills/`) — source of truth, author's working copies
//! - **Public zone** (`skills/`) — export surface, generated by `kask skill publish`
//
//! The loader scans both zones, parses YAML front matter from each SKILL.md,
//! validates zone-vs-visibility consistency, and registers skills into a
//! `SkillRegistryIndex`. Zone-vs-visibility mismatches emit a warning but
//! do not block registration — the `visibility` field in SKILL.md wins.

use hkask_types::TemplateType;
use hkask_types::ports::{Skill, SkillRegistryIndex, SkillZone};
use hkask_types::visibility::Visibility;
use std::collections::HashMap;
use std::fs;
use std::path::{Path, PathBuf};

/// Parsed SKILL.md front matter.
#[derive(Debug, Clone, serde::Deserialize)]
pub struct SkillFrontMatter {
    pub name: String,
    #[serde(default)]
    pub visibility: Option<String>,
    #[serde(default)]
    pub namespace: Option<String>,
    #[serde(default)]
    pub description: Option<String>,
}

impl Default for SkillFrontMatter {
    fn default() -> Self {
        Self {
            name: String::new(),
            visibility: None,
            namespace: None,
            description: None,
        }
    }
}

/// Result of loading skills from both zones.
#[derive(Debug)]
pub struct SkillLoadResult {
    pub loaded: Vec<Skill>,
    pub warnings: Vec<String>,
}

/// Skill loader — discovers SKILL.md files from both zones, parses front matter,
/// validates zone-vs-visibility consistency, and registers skills.
pub struct SkillLoader {
    /// Root directory for skill discovery (typically the project root).
    project_root: PathBuf,
}

impl SkillLoader {
    /// Create a new skill loader rooted at `project_root`.
    pub fn new(project_root: impl Into<PathBuf>) -> Self {
        Self {
            project_root: project_root.into(),
        }
    }

    /// Discover and load skills from both zones, registering them into the registry.
    pub fn load_into(&self, registry: &mut dyn SkillRegistryIndex) -> SkillLoadResult {
        let mut result = SkillLoadResult {
            loaded: Vec::new(),
            warnings: Vec::new(),
        };

        // Scan private zone first (source of truth), then public zone (export surface).
        for zone in [SkillZone::Private, SkillZone::Public] {
            let zone_dir = self.project_root.join(zone.directory());
            if !zone_dir.exists() {
                continue;
            }

            let discovered = match Self::discover_skills(&zone_dir) {
                Ok(skills) => skills,
                Err(e) => {
                    result.warnings.push(format!(
                        "Failed to scan {} zone at {}: {}",
                        zone.as_str(),
                        zone_dir.display(),
                        e
                    ));
                    continue;
                }
            };

            for skill_dir in discovered {
                match self.load_skill(&skill_dir, zone) {
                    Ok(skill) => {
                        // Validate zone-vs-visibility consistency.
                        if let Some(warning) = Self::check_zone_visibility(&skill, zone) {
                            result.warnings.push(warning);
                        }
                        registry.register_skill(skill.clone());
                        result.loaded.push(skill);
                    }
                    Err(e) => {
                        result.warnings.push(format!(
                            "Failed to load skill from {}: {}",
                            skill_dir.display(),
                            e
                        ));
                    }
                }
            }
        }

        result
    }

    /// Discover skill directories within a zone directory.
    /// A skill directory is any directory containing a `SKILL.md` file.
    fn discover_skills(zone_dir: &Path) -> Result<Vec<PathBuf>, String> {
        let mut skill_dirs = Vec::new();
        let entries = fs::read_dir(zone_dir).map_err(|e| e.to_string())?;

        for entry in entries {
            let entry = entry.map_err(|e| e.to_string())?;
            let path = entry.path();
            if path.is_dir() && path.join("SKILL.md").exists() {
                skill_dirs.push(path);
            }
        }

        skill_dirs.sort();
        Ok(skill_dirs)
    }

    /// Load a single skill from its directory.
    fn load_skill(&self, skill_dir: &Path, zone: SkillZone) -> Result<Skill, String> {
        let skill_md_path = skill_dir.join("SKILL.md");
        let content = fs::read_to_string(&skill_md_path)
            .map_err(|e| format!("read {}: {}", skill_md_path.display(), e))?;

        let front_matter = Self::parse_front_matter(&content)?;

        // Derive ID and namespace from directory name + zone.
        //
        // In the public zone, directory names are `<namespace>--<id>` (e.g. "alice--diagnose").
        // In the private zone, directory names are just `<id>` (no namespace).
        let dir_name = skill_dir
            .file_name()
            .and_then(|n| n.to_str())
            .unwrap_or(&front_matter.name);

        let (namespace_from_dir, id_from_dir) = match zone {
            SkillZone::Public => Skill::parse_qualified_id(dir_name)
                .unwrap_or_else(|| (String::new(), dir_name.to_string())),
            SkillZone::Private => (String::new(), dir_name.to_string()),
        };

        // Front matter namespace wins over directory-inferred namespace.
        // Directory structure is the fallback for skills published before
        // namespace was added to SKILL.md.
        let namespace = front_matter.namespace.or_else(|| {
            if namespace_from_dir.is_empty() {
                None
            } else {
                Some(namespace_from_dir)
            }
        });
        let id = id_from_dir;

        let visibility = front_matter
            .visibility
            .as_deref()
            .and_then(Visibility::parse_str)
            .unwrap_or(Visibility::Private);

        let mut skill = Skill::new(&id, TemplateType::FlowDef)
            .with_visibility(visibility)
            .with_zone(zone);

        if let Some(ref ns) = namespace {
            skill = skill.with_namespace(ns.clone());
        }

        skill.compute_content_hash();

        Ok(skill)
    }

    /// Parse YAML front matter from a SKILL.md file.
    /// Expects `---\n` delimiters at the start and end of the front matter block.
    pub fn parse_front_matter(content: &str) -> Result<SkillFrontMatter, String> {
        let content = content.trim_start();

        if !content.starts_with("---") {
            // No front matter — return default with empty name.
            return Ok(SkillFrontMatter::default());
        }

        // Find the closing `---`.
        let after_first = &content[3..];
        let rest = after_first.trim_start_matches(['-', '\n', '\r']);

        let end_marker = rest.find("\n---").ok_or_else(|| {
            "SKILL.md front matter: opening `---` found but no closing `---`".to_string()
        })?;

        let yaml_str = &rest[..end_marker];

        let fm: HashMap<String, String> = serde_yaml::from_str(yaml_str)
            .map_err(|e| format!("SKILL.md YAML parse error: {}", e))?;

        let name = fm.get("name").cloned().unwrap_or_default();
        let visibility = fm.get("visibility").cloned();
        let namespace = fm.get("namespace").cloned();
        let description = fm.get("description").cloned();

        Ok(SkillFrontMatter {
            name,
            visibility,
            namespace,
            description,
        })
    }

    /// Check zone-vs-visibility consistency.
    ///
    /// Rules:
    /// - A skill in the public zone MUST have `visibility: public` or `visibility: shared`.
    /// - A skill in the private zone MAY have any visibility.
    ///
    /// If they disagree, the `visibility` field wins and a warning is emitted.
    fn check_zone_visibility(skill: &Skill, zone: SkillZone) -> Option<String> {
        match (zone, skill.visibility) {
            (SkillZone::Public, Visibility::Private) => Some(format!(
                "Skill '{}' is in the public zone ({}) but declares visibility: private. \
                 The declared visibility wins — this skill will be treated as private. \
                 Move it to .agents/skills/ or change visibility to 'public' or 'shared'.",
                skill.id,
                zone.directory()
            )),
            _ => None,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use hkask_types::ports::SkillRegistryIndex;

    /// Minimal in-memory registry for testing.
    struct TestRegistry {
        skills: HashMap<String, Skill>,
    }

    impl TestRegistry {
        fn new() -> Self {
            Self {
                skills: HashMap::new(),
            }
        }
    }

    impl SkillRegistryIndex for TestRegistry {
        fn register_skill(&mut self, skill: Skill) {
            self.skills.insert(skill.id.clone(), skill);
        }
        fn get_skill(&self, id: &str) -> Option<Skill> {
            self.skills.get(id).cloned()
        }
        fn list_skills(&self) -> Vec<Skill> {
            self.skills.values().cloned().collect()
        }
        fn list_skills_by_visibility(&self, visibility: Visibility) -> Vec<Skill> {
            self.skills
                .values()
                .filter(|s| s.visibility == visibility)
                .cloned()
                .collect()
        }
        fn skills_by_domain(&self, _domain: TemplateType) -> Vec<Skill> {
            Vec::new()
        }
        fn skills_referencing_template(&self, _template_id: &str) -> Vec<Skill> {
            Vec::new()
        }
        fn remove_skill(&mut self, id: &str) -> Option<Skill> {
            self.skills.remove(id)
        }
    }

    #[test]
    fn parse_front_matter_with_visibility() {
        let content = "---\nname: test-skill\nvisibility: public\ndescription: A test\n---\n\nBody";
        let fm = SkillLoader::parse_front_matter(content).unwrap();
        assert_eq!(fm.name, "test-skill");
        assert_eq!(fm.visibility.as_deref(), Some("public"));
        assert_eq!(fm.description.as_deref(), Some("A test"));
    }

    #[test]
    fn parse_front_matter_without_visibility() {
        let content = "---\nname: test-skill\ndescription: A test\n---\n\nBody";
        let fm = SkillLoader::parse_front_matter(content).unwrap();
        assert_eq!(fm.name, "test-skill");
        assert!(fm.visibility.is_none());
    }

    #[test]
    fn parse_front_matter_no_front_matter() {
        let content = "Just some content without front matter";
        let fm = SkillLoader::parse_front_matter(content).unwrap();
        assert!(fm.name.is_empty());
    }

    #[test]
    fn check_zone_visibility_public_zone_private_visibility_warns() {
        let skill = Skill::new("test", TemplateType::FlowDef)
            .with_visibility(Visibility::Private)
            .with_zone(SkillZone::Public);
        let warning = SkillLoader::check_zone_visibility(&skill, SkillZone::Public);
        assert!(warning.is_some());
        assert!(warning.unwrap().contains("public zone"));
    }

    #[test]
    fn check_zone_visibility_public_zone_public_visibility_no_warn() {
        let skill = Skill::new("test", TemplateType::FlowDef)
            .with_visibility(Visibility::Public)
            .with_zone(SkillZone::Public);
        let warning = SkillLoader::check_zone_visibility(&skill, SkillZone::Public);
        assert!(warning.is_none());
    }

    #[test]
    fn check_zone_visibility_private_zone_any_visibility_no_warn() {
        for vis in [Visibility::Private, Visibility::Public, Visibility::Shared] {
            let skill = Skill::new("test", TemplateType::FlowDef)
                .with_visibility(vis)
                .with_zone(SkillZone::Private);
            let warning = SkillLoader::check_zone_visibility(&skill, SkillZone::Private);
            assert!(warning.is_none());
        }
    }

    #[test]
    fn default_visibility_is_private() {
        let skill = Skill::new("test", TemplateType::FlowDef);
        assert_eq!(skill.visibility, Visibility::Private);
        assert_eq!(skill.zone, SkillZone::Private);
    }

    #[test]
    fn content_hash_includes_visibility_and_zone() {
        let mut skill_a = Skill::new("test", TemplateType::FlowDef)
            .with_visibility(Visibility::Private)
            .with_zone(SkillZone::Private);
        skill_a.compute_content_hash();

        let mut skill_b = Skill::new("test", TemplateType::FlowDef)
            .with_visibility(Visibility::Public)
            .with_zone(SkillZone::Private);
        skill_b.compute_content_hash();

        let mut skill_c = Skill::new("test", TemplateType::FlowDef)
            .with_visibility(Visibility::Private)
            .with_zone(SkillZone::Public);
        skill_c.compute_content_hash();

        // Different visibility → different hash
        assert_ne!(skill_a.content_hash, skill_b.content_hash);
        // Different zone → different hash
        assert_ne!(skill_a.content_hash, skill_c.content_hash);
    }

    #[test]
    fn list_skills_visible_to_private_sees_all() {
        let mut reg = TestRegistry::new();
        reg.register_skill(
            Skill::new("s1", TemplateType::FlowDef).with_visibility(Visibility::Private),
        );
        reg.register_skill(
            Skill::new("s2", TemplateType::FlowDef).with_visibility(Visibility::Public),
        );
        reg.register_skill(
            Skill::new("s3", TemplateType::FlowDef).with_visibility(Visibility::Shared),
        );

        let visible = reg.list_skills_visible_to(Visibility::Private);
        assert_eq!(visible.len(), 3);
    }

    #[test]
    fn list_skills_visible_to_public_sees_only_public_and_shared() {
        let mut reg = TestRegistry::new();
        reg.register_skill(
            Skill::new("s1", TemplateType::FlowDef).with_visibility(Visibility::Private),
        );
        reg.register_skill(
            Skill::new("s2", TemplateType::FlowDef).with_visibility(Visibility::Public),
        );
        reg.register_skill(
            Skill::new("s3", TemplateType::FlowDef).with_visibility(Visibility::Shared),
        );

        let visible = reg.list_skills_visible_to(Visibility::Public);
        assert_eq!(visible.len(), 2);
        let ids: Vec<&str> = visible.iter().map(|s| s.id.as_str()).collect();
        assert!(ids.contains(&"s2"));
        assert!(ids.contains(&"s3"));
        assert!(!ids.contains(&"s1"));
    }

    #[test]
    fn qualified_id_with_namespace() {
        let skill = Skill::new("diagnose", TemplateType::FlowDef).with_namespace("alice");
        assert_eq!(skill.qualified_id(), "alice--diagnose");
    }

    #[test]
    fn qualified_id_without_namespace() {
        let skill = Skill::new("diagnose", TemplateType::FlowDef);
        assert_eq!(skill.qualified_id(), "diagnose");
    }

    #[test]
    fn parse_qualified_id_valid() {
        let result = Skill::parse_qualified_id("alice--diagnose");
        assert_eq!(result, Some(("alice".to_string(), "diagnose".to_string())));
    }

    #[test]
    fn parse_qualified_id_no_separator() {
        assert!(Skill::parse_qualified_id("diagnose").is_none());
    }

    #[test]
    fn parse_qualified_id_empty_parts() {
        assert!(Skill::parse_qualified_id("--diagnose").is_none());
        assert!(Skill::parse_qualified_id("alice--").is_none());
    }

    #[test]
    fn namespace_collision_prevention() {
        // Two users publish the same skill name — no collision
        let skill_a = Skill::new("diagnose", TemplateType::FlowDef)
            .with_namespace("alice")
            .with_zone(SkillZone::Public);
        let skill_b = Skill::new("diagnose", TemplateType::FlowDef)
            .with_namespace("bob")
            .with_zone(SkillZone::Public);

        assert_eq!(skill_a.qualified_id(), "alice--diagnose");
        assert_eq!(skill_b.qualified_id(), "bob--diagnose");
        assert_ne!(skill_a.qualified_id(), skill_b.qualified_id());
    }
}
