//! Skill loader — discovers, parses, and registers SKILL.md files from both zones
//!
//! Two-zone model (src→dist pattern):
//! - **Private zone** (`.agents/skills/`) — source of truth, author's working copies
//! - **Public zone** (`skills/`) — export surface, generated by `kask skill publish`
//!
//! The loader scans both zones, parses YAML front matter from each SKILL.md,
//! validates zone-vs-visibility consistency, and registers skills into a
//! `SkillRegistryIndex`. Zone-vs-visibility mismatches emit a warning but
//! do not block registration — the `visibility` field in SKILL.md wins.


use hkask_types::ports::{Skill, SkillRegistryIndex, SkillZone};
use hkask_types::template_type::TemplateType;
use hkask_types::visibility::Visibility;
use serde::Deserialize;
use std::collections::HashMap;
use std::fs;
use std::path::{Path, PathBuf};

/// Parsed SKILL.md front matter.
#[derive(Debug, Clone, Default, serde::Deserialize)]
pub struct SkillFrontMatter {
    #[serde(default)]
    pub name: String,
    #[serde(default)]
    pub visibility: Option<String>,
    #[serde(default)]
    pub namespace: Option<String>,
    #[serde(default)]
    pub description: Option<String>,
}

/// Minimal manifest shape used to infer a skill's domain from its registry layer.
#[derive(Debug, Default, Deserialize)]
struct SkillManifest {
    #[serde(default)]
    templates: Vec<ManifestTemplateEntry>,
}

#[derive(Debug, Default, Deserialize)]
struct ManifestTemplateEntry {
    #[serde(default)]
    #[serde(rename = "type")]
    template_type: String,
}

/// Result of loading skills from both zones.
#[derive(Debug)]
pub struct SkillLoadResult {
    pub loaded: Vec<Skill>,
    pub warnings: Vec<String>,
}

/// Skill loader — discovers SKILL.md files from both zones, parses front matter,
/// validates zone-vs-visibility consistency, and registers skills.
pub struct SkillLoader {
    /// Root directory for skill discovery (typically the project root).
    project_root: PathBuf,
}

impl SkillLoader {
    /// Create a new skill loader rooted at `project_root`.
    ///
    /// \[P3\] Motivating: Generative Space — loader for skill registry entries
    pub fn new(project_root: impl Into<PathBuf>) -> Self {
        Self {
            project_root: project_root.into(),
        }
    }

    /// Discover and load skills from both zones, registering them into the registry.
    ///
    /// \[P3\] Motivating: Generative Space — loads skill into registry
    pub fn load_into(&self, registry: &mut dyn SkillRegistryIndex) -> SkillLoadResult {
        let mut result = SkillLoadResult {
            loaded: Vec::new(),
            warnings: Vec::new(),
        };

        // Scan private zone first (source of truth), then public zone (export surface).
        for zone in [SkillZone::Private, SkillZone::Public] {
            let zone_dir = self.project_root.join(zone.directory());
            if !zone_dir.exists() {
                continue;
            }

            let discovered = match Self::discover_skills(&zone_dir) {
                Ok(skills) => skills,
                Err(e) => {
                    result.warnings.push(format!(
                        "Failed to scan {} zone at {}: {}",
                        zone.as_str(),
                        zone_dir.display(),
                        e
                    ));
                    continue;
                }
            };

            for skill_dir in discovered {
                match self.load_skill(&skill_dir, zone) {
                    Ok(skill) => {
                        // Validate zone-vs-visibility consistency.
                        if let Some(warning) = Self::check_zone_visibility(&skill, zone) {
                            result.warnings.push(warning);
                        }
                        registry.register_skill(skill.clone());
                        result.loaded.push(skill);
                    }
                    Err(e) => {
                        result.warnings.push(format!(
                            "Failed to load skill from {}: {}",
                            skill_dir.display(),
                            e
                        ));
                    }
                }
            }
        }

        result
    }

    /// Discover skill directories within a zone directory.
    /// A skill directory is any directory containing a `SKILL.md` file.
    fn discover_skills(zone_dir: &Path) -> Result<Vec<PathBuf>, String> {
        let mut skill_dirs = Vec::new();
        let entries = fs::read_dir(zone_dir).map_err(|e| e.to_string())?;

        for entry in entries {
            let entry = entry.map_err(|e| e.to_string())?;
            let path = entry.path();
            if path.is_dir() && path.join("SKILL.md").exists() {
                skill_dirs.push(path);
            }
        }

        skill_dirs.sort();
        Ok(skill_dirs)
    }

    /// Load a single skill from its directory.
    fn load_skill(&self, skill_dir: &Path, zone: SkillZone) -> Result<Skill, String> {
        let skill_md_path = skill_dir.join("SKILL.md");
        let content = fs::read_to_string(&skill_md_path)
            .map_err(|e| format!("read {}: {}", skill_md_path.display(), e))?;

        let front_matter = Self::parse_front_matter(&content)?;

        // Derive ID and namespace from directory name + zone.
        //
        // In the public zone, directory names are `<namespace>--<id>` (e.g. "alice--diagnose").
        // In the private zone, directory names are just `<id>` (no namespace).
        let dir_name = skill_dir
            .file_name()
            .and_then(|n| n.to_str())
            .unwrap_or(&front_matter.name);

        let (namespace_from_dir, id_from_dir) = match zone {
            SkillZone::Public => Skill::parse_qualified_id(dir_name)
                .unwrap_or_else(|| (String::new(), dir_name.to_string())),
            SkillZone::Private => (String::new(), dir_name.to_string()),
        };

        // Front matter namespace wins over directory-inferred namespace.
        // Directory structure is the fallback for skills published before
        // namespace was added to SKILL.md.
        let namespace = front_matter.namespace.or({
            if namespace_from_dir.is_empty() {
                None
            } else {
                Some(namespace_from_dir)
            }
        });
        let id = id_from_dir;

        let visibility = front_matter
            .visibility
            .as_deref()
            .and_then(Visibility::parse_str)
            .unwrap_or(Visibility::Private);

        let domain = self.infer_domain_from_registry(&id);

        let mut skill = Skill::new(&id, domain)
            .with_visibility(visibility)
            .with_zone(zone);

        if let Some(ref ns) = namespace {
            skill = skill.with_namespace(ns.clone());
        }

        skill.compute_content_hash();

        Ok(skill)
    }

    /// Infer the skill's domain from its registry layer manifest.
    ///
    /// If `registry/templates/<id>/manifest.yaml` exists under the project root,
    /// use the most representative template type: FlowDef if any flow is declared,
    /// otherwise KnowAct if any cognition template is present, otherwise WordAct.
    /// If no registry layer exists, default to KnowAct because a Zed-only SKILL.md
    /// is a reasoning companion guide.
    ///
    /// \[P3\] Motivating: Generative Space — infers skill domain from registry contents
    fn infer_domain_from_registry(&self, id: &str) -> TemplateType {
        let registry_manifest = self
            .project_root
            .join("registry")
            .join("templates")
            .join(id)
            .join("manifest.yaml");

        let content = match fs::read_to_string(&registry_manifest) {
            Ok(c) => c,
            Err(_) => return TemplateType::KnowAct,
        };

        let manifest: SkillManifest = match serde_yaml_neo::from_str(&content) {
            Ok(m) => m,
            Err(_) => return TemplateType::KnowAct,
        };

        let mut has_flowdef = false;
        let mut has_knowact = false;
        let mut has_wordact = false;
        for entry in &manifest.templates {
            match entry.template_type.as_str() {
                "FlowDef" | "flowdef" => has_flowdef = true,
                "KnowAct" | "knowact" => has_knowact = true,
                "WordAct" | "wordact" => has_wordact = true,
                _ => {}
            }
        }

        if has_flowdef {
            TemplateType::FlowDef
        } else if has_knowact {
            TemplateType::KnowAct
        } else if has_wordact {
            TemplateType::WordAct
        } else {
            TemplateType::KnowAct
        }
    }

    /// Parse YAML front matter from a SKILL.md file.
    /// Expects `---\n` delimiters at the start and end of the front matter block.
    ///
    /// \[P3\] Motivating: Generative Space — parses skill front matter metadata
    pub fn parse_front_matter(content: &str) -> Result<SkillFrontMatter, String> {
        let content = content.trim_start();

        if !content.starts_with("---") {
            // No front matter — return default with empty name.
            return Ok(SkillFrontMatter::default());
        }

        // Find the closing `---`.
        let after_first = &content[3..];
        let rest = after_first.trim_start_matches(['-', '\n', '\r']);

        let end_marker = rest.find("\n---").ok_or_else(|| {
            "SKILL.md front matter: opening `---` found but no closing `---`".to_string()
        })?;

        let yaml_str = &rest[..end_marker];

        let fm: HashMap<String, serde_yaml_neo::Value> = serde_yaml_neo::from_str(yaml_str)
            .map_err(|e| format!("SKILL.md YAML parse error: {}", e))?;

        let as_string = |key: &str| fm.get(key).and_then(|v| v.as_str()).map(|s| s.to_string());

        let name = as_string("name").unwrap_or_default();
        let visibility = as_string("visibility");
        let namespace = as_string("namespace");
        let description = as_string("description");

        Ok(SkillFrontMatter {
            name,
            visibility,
            namespace,
            description,
        })
    }

    /// Check zone-vs-visibility consistency.
    ///
    /// Rules:
    /// - A skill in the public zone MUST have `visibility: public` or `visibility: shared`.
    /// - A skill in the private zone MAY have any visibility.
    ///
    /// If they disagree, the `visibility` field wins and a warning is emitted.
    fn check_zone_visibility(skill: &Skill, zone: SkillZone) -> Option<String> {
        match (zone, skill.visibility) {
            (SkillZone::Public, Visibility::Private) => Some(format!(
                "Skill '{}' is in the public zone ({}) but declares visibility: private. \
                 The declared visibility wins — this skill will be treated as private. \
                 Move it to .agents/skills/ or change visibility to 'public' or 'shared'.",
                skill.id,
                zone.directory()
            )),
            _ => None,
        }
    }
}
