apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: conduit-data
  namespace: hkask-conduit
spec:
  storageClassName: hcloud-volumes
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
