//! Curator service — escalation management and metacognition.
//!
//! `CuratorService` replaces the duplicated escalation queue operations
//! across CLI and API surfaces. Each surface constructs a `CuratorContext`
//! from its own state and delegates business logic to this service.
//!
//! # Design decisions
//!
//! - **Constraint: Prohibition (P1)** — MCP servers do NOT use this service.
//!   They continue using `EscalationQueue` directly because they run in
//!   separate processes and cannot share `CuratorContext`.
//! - **Constraint: Guideline** — `resolve_escalation` and `dismiss_escalation`
//!   verify existence before mutating. This normalizes behavior: the API
//!   currently checks, the CLI doesn't. Both surfaces will get the same
//!   `ServiceError::EscalationNotFound` error.
//! - **Depth test** — Deleting this module would cause escalation queue
//!   construction logic and existence checks to reappear in 8+ call sites.
//!   Passes deletion test.
//! - **Strangler fig** — `CuratorContext` is a lightweight struct that surfaces
//!   construct from their own state. For escalation-only operations, only
//!   `escalation_queue` is required. For `run_metacognition`, `cns_runtime`
//!   and `dispatch` are also required.
//! - **`run_metacognition`** constructs a fresh `CuratorAgent` each call.
//!   This matches the CLI's current behavior. The API doesn't run metacognition
//!   cycles — it only calls `escalation_stats()`. A shared MetacognitionLoop
//!   is a future Hypothesis.

use std::sync::Arc;

use hkask_agents::EscalationEntry;
use hkask_agents::EscalationQueue;
use hkask_agents::communication::MessageDispatch;
use hkask_agents::curator_agent::CuratorAgent;
use hkask_agents::escalation::EscalationStats;
use hkask_cns::CnsRuntime;
use hkask_types::CuratorHandle;

use crate::ServiceError;

/// Lightweight context for `CuratorService` calls.
///
/// Contains only the fields needed for escalation and metacognition
/// operations. Construct from surface state (CLI `ReplState`, API
/// `ApiState`) or from `ServiceContext` parts.
///
/// For escalation-only operations (list, get, resolve, dismiss, stats),
/// only `escalation_queue` is required — `cns_runtime` and `dispatch`
/// can be `None`.
///
/// For `run_metacognition`, `cns_runtime` and `dispatch` must be `Some`.
/// Calling `run_metacognition` without them returns
/// `ServiceError::Cns("...")`.
pub struct CuratorContext {
    /// Escalation queue — always required.
    pub escalation_queue: Arc<EscalationQueue>,
    /// CNS runtime — required for `run_metacognition`.
    pub cns_runtime: Option<Arc<CnsRuntime>>,
    /// Message dispatch — required for `run_metacognition`.
    pub dispatch: Option<Arc<MessageDispatch>>,
}

impl CuratorContext {
    /// Construct from individual parts.
    ///
    /// For escalation-only operations, pass `None` for `cns_runtime` and
    /// `dispatch`:
    /// ```ignore
    /// let ctx = CuratorContext::from_parts(escalation_queue, None, None);
    /// ```
    ///
    /// For metacognition operations, provide all three:
    /// ```ignore
    /// let ctx = CuratorContext::from_parts(
    ///     escalation_queue,
    ///     Some(cns_runtime),
    ///     Some(dispatch),
    /// );
    /// ```
    pub fn from_parts(
        escalation_queue: Arc<EscalationQueue>,
        cns_runtime: Option<Arc<CnsRuntime>>,
        dispatch: Option<Arc<MessageDispatch>>,
    ) -> Self {
        Self {
            escalation_queue,
            cns_runtime,
            dispatch,
        }
    }
}

/// Service-layer summary of a metacognition cycle.
///
/// Captures the public fields from `HealthSnapshot`. The `bot_status_reports`
/// field is `pub(crate)` in the domain crate, so this summary exposes
/// the structured data that surfaces can adapt (CLI prints `summary_text`,
/// API constructs JSON response).
#[derive(Debug)]
pub struct MetacognitionSummary {
    /// Human-readable summary text generated by the metacognition loop.
    pub summary_text: String,
    /// CNS health status string (e.g., "nominal", "degraded").
    pub cns_health: String,
    /// Variety counters per domain (domain name, current variety).
    pub variety_counters: Vec<(String, u64)>,
    /// Number of critical alerts in the system.
    pub critical_alerts: usize,
    /// Total number of alerts in the system.
    pub total_alerts: usize,
}

/// Curator service — escalation management and metacognition.
///
/// Use `CuratorService::list_escalations()` etc. to delegate escalation
/// operations through the service layer. Surfaces construct a
/// `CuratorContext` from their own state and call service methods.
pub struct CuratorService;

impl CuratorService {
    /// List all pending escalations.
    ///
    /// # REQ: svc-cur-001 — list_escalations returns all pending escalations
    pub fn list_escalations(ctx: &CuratorContext) -> Result<Vec<EscalationEntry>, ServiceError> {
        ctx.escalation_queue
            .list_pending()
            .map_err(ServiceError::from)
    }

    /// Get a specific escalation by ID.
    ///
    /// # REQ: svc-cur-002 — get_escalation returns escalation by ID or None
    pub fn get_escalation(
        ctx: &CuratorContext,
        id: &str,
    ) -> Result<Option<EscalationEntry>, ServiceError> {
        ctx.escalation_queue.get(id).map_err(ServiceError::from)
    }

    /// Resolve an escalation by ID.
    ///
    /// Verifies the escalation exists before resolving. Returns
    /// `ServiceError::EscalationNotFound` if the escalation doesn't exist.
    ///
    /// # REQ: svc-cur-003 — resolve_escalation verifies existence then resolves
    pub fn resolve_escalation(
        ctx: &CuratorContext,
        id: &str,
        resolved_by: &str,
    ) -> Result<(), ServiceError> {
        let entry = ctx.escalation_queue.get(id)?;
        if entry.is_none() {
            return Err(ServiceError::EscalationNotFound(id.to_string()));
        }
        ctx.escalation_queue
            .resolve(id, resolved_by)
            .map_err(ServiceError::from)
    }

    /// Dismiss an escalation by ID.
    ///
    /// Verifies the escalation exists before dismissing. Returns
    /// `ServiceError::EscalationNotFound` if the escalation doesn't exist.
    ///
    /// # REQ: svc-cur-004 — dismiss_escalation verifies existence then dismisses
    pub fn dismiss_escalation(
        ctx: &CuratorContext,
        id: &str,
        dismissed_by: &str,
    ) -> Result<(), ServiceError> {
        let entry = ctx.escalation_queue.get(id)?;
        if entry.is_none() {
            return Err(ServiceError::EscalationNotFound(id.to_string()));
        }
        ctx.escalation_queue
            .dismiss(id, dismissed_by)
            .map_err(ServiceError::from)
    }

    /// Get aggregated escalation statistics.
    ///
    /// # REQ: svc-cur-005 — escalation_stats returns total/pending/resolved/dismissed counts
    pub fn escalation_stats(ctx: &CuratorContext) -> Result<EscalationStats, ServiceError> {
        ctx.escalation_queue.stats().map_err(ServiceError::from)
    }

    /// Run a metacognition cycle and return a summary.
    ///
    /// Requires `cns_runtime` and `dispatch` in the `CuratorContext`.
    /// Returns `ServiceError::Cns` if either is missing.
    ///
    /// # REQ: svc-cur-006 — run_metacognition executes a full cycle and returns summary
    pub async fn run_metacognition(
        ctx: &CuratorContext,
    ) -> Result<MetacognitionSummary, ServiceError> {
        let cns = ctx.cns_runtime.as_ref().ok_or_else(|| {
            ServiceError::Cns("CNS runtime required for metacognition".to_string())
        })?;
        let dispatch = ctx.dispatch.as_ref().ok_or_else(|| {
            ServiceError::Cns("Message dispatch required for metacognition".to_string())
        })?;

        let curator_handle = CuratorHandle::system();
        let agents_context = Arc::new(hkask_agents::CuratorContext::new(
            curator_handle,
            Arc::clone(cns),
            Arc::clone(dispatch),
            Arc::clone(&ctx.escalation_queue),
        ));
        let agent = CuratorAgent::new(agents_context);
        let metacognition = agent.metacognition();
        let snapshot = metacognition.run_cycle().await?;

        Ok(MetacognitionSummary {
            summary_text: metacognition.generate_summary(&snapshot),
            cns_health: snapshot.cns_health,
            variety_counters: snapshot.variety_counters,
            critical_alerts: snapshot.critical_alerts,
            total_alerts: snapshot.total_alerts,
        })
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use hkask_storage::in_memory_db;

    fn test_queue() -> Arc<EscalationQueue> {
        Arc::new(
            EscalationQueue::new(in_memory_db().conn_arc()).expect("queue init should succeed"),
        )
    }

    // REQ: svc-cur-001 — list_escalations returns all pending escalations
    #[test]
    fn list_escalations_delegates_to_queue() {
        let ctx = CuratorContext::from_parts(test_queue(), None, None);
        let result = CuratorService::list_escalations(&ctx);
        assert!(result.is_ok(), "list_escalations should succeed");
        assert!(
            result.unwrap().is_empty(),
            "empty queue should return no escalations"
        );
    }

    // REQ: svc-cur-002 — get_escalation returns escalation by ID or None
    #[test]
    fn get_escalation_returns_none_for_missing_id() {
        let ctx = CuratorContext::from_parts(test_queue(), None, None);
        let result = CuratorService::get_escalation(&ctx, "nonexistent-id");
        assert!(result.is_ok(), "get_escalation should succeed");
        assert!(
            result.unwrap().is_none(),
            "nonexistent ID should return None"
        );
    }

    // REQ: svc-cur-003 — resolve_escalation verifies existence then resolves
    #[test]
    fn resolve_escalation_returns_not_found_for_missing_id() {
        let ctx = CuratorContext::from_parts(test_queue(), None, None);
        let result = CuratorService::resolve_escalation(&ctx, "nonexistent-id", "admin");
        assert!(
            result.is_err(),
            "resolve should fail for nonexistent escalation"
        );
        match result {
            Err(ServiceError::EscalationNotFound(id)) => {
                assert_eq!(id, "nonexistent-id");
            }
            other => panic!("expected EscalationNotFound, got {:?}", other),
        }
    }

    // REQ: svc-cur-004 — dismiss_escalation verifies existence then dismisses
    #[test]
    fn dismiss_escalation_returns_not_found_for_missing_id() {
        let ctx = CuratorContext::from_parts(test_queue(), None, None);
        let result = CuratorService::dismiss_escalation(&ctx, "nonexistent-id", "admin");
        assert!(
            result.is_err(),
            "dismiss should fail for nonexistent escalation"
        );
        match result {
            Err(ServiceError::EscalationNotFound(id)) => {
                assert_eq!(id, "nonexistent-id");
            }
            other => panic!("expected EscalationNotFound, got {:?}", other),
        }
    }

    // REQ: svc-cur-005 — escalation_stats returns total/pending/resolved/dismissed counts
    #[test]
    fn escalation_stats_returns_counts_after_adding_escalation() {
        // Note: stats() on an empty table returns NULL for SUM columns,
        // which causes a deserialization error. We test with at least one
        // escalation to verify the stats path works correctly.
        let queue = test_queue();
        let ctx = CuratorContext::from_parts(queue.clone(), None, None);

        // Add a pending escalation
        let id = queue
            .add(
                hkask_types::TemplateID::new(),
                hkask_types::BotID::new(),
                "test output".to_string(),
                0.95,
                0,
                "test context".to_string(),
            )
            .expect("add should succeed");

        let stats = CuratorService::escalation_stats(&ctx).expect("stats should succeed");
        assert_eq!(
            stats.total, 1,
            "queue with one escalation should have 1 total"
        );
        assert_eq!(
            stats.pending, 1,
            "pending escalation should count as pending"
        );
        assert_eq!(stats.resolved, 0, "no resolved escalation");

        // Resolve it and check again
        CuratorService::resolve_escalation(&ctx, &id, "tester").expect("resolve should succeed");
        let stats = CuratorService::escalation_stats(&ctx).expect("stats should succeed");
        assert_eq!(
            stats.pending, 0,
            "resolved escalation should not be pending"
        );
        assert_eq!(
            stats.resolved, 1,
            "resolved escalation should count as resolved"
        );
    }

    // REQ: svc-cur-006 — run_metacognition requires CNS runtime and dispatch
    #[test]
    fn run_metacognition_returns_error_without_cns_runtime() {
        let ctx = CuratorContext::from_parts(test_queue(), None, None);
        let rt = tokio::runtime::Runtime::new().expect("runtime should start");
        let result = rt.block_on(CuratorService::run_metacognition(&ctx));
        assert!(result.is_err(), "run_metacognition should fail without CNS");
        match result {
            Err(ServiceError::Cns(msg)) => {
                assert!(
                    msg.contains("CNS runtime required"),
                    "error should mention CNS runtime requirement, got: {}",
                    msg
                );
            }
            other => panic!("expected Cns error, got {:?}", other),
        }
    }
}
