#!/bin/bash
# =============================================================================
# hKask Axolotl LoRA Trainer — Entrypoint (bash only, no Python)
# =============================================================================
# The axolotl config is generated by Rust (AxolotlHarness::render_config) and
# passed as the HKASK_AXOLOTL_CONFIG env var. This script writes it to a file
# and runs `axolotl train`.
#
# Flow:
#   1. Write the axolotl config from HKASK_AXOLOTL_CONFIG to /workspace/config.yml
#   2. Login to HuggingFace (if HF_TOKEN set)
#   3. Run axolotl training
#   4. Upload adapter to HuggingFace (if HKASK_HF_MODEL_REPOSITORY set)
#   5. Write completion manifest
#   6. Keep container alive for SSH debugging
# =============================================================================

set -euo pipefail

echo "============================================"
echo "hKask Axolotl LoRA Trainer"
echo "============================================"
echo "Job ID: ${HKASK_JOB_ID:-unknown}"
echo "Model repo: ${HKASK_HF_MODEL_REPOSITORY:-none}"
echo "============================================"
echo

# ── Step 1: Write the axolotl config ──────────────────────────────────────
if [ -z "${HKASK_AXOLOTL_CONFIG:-}" ]; then
    echo "ERROR: HKASK_AXOLOTL_CONFIG is required (generated by Rust AxolotlHarness)"
    exit 1
fi

echo "Writing axolotl config..."
echo "$HKASK_AXOLOTL_CONFIG" > /workspace/config.yml
echo "Config written to /workspace/config.yml"
echo "--- Config preview ---"
head -20 /workspace/config.yml
echo "..."
echo

# ── Step 2: Login to HuggingFace ─────────────────────────────────────────
if [ -n "${HKASK_HF_TOKEN:-}" ]; then
    echo "Logging in to HuggingFace..."
    huggingface-cli login --token "$HKASK_HF_TOKEN" --add-to-git-credential 2>/dev/null || \
    echo "huggingface-cli not available, HF_TOKEN will be used by axolotl directly"
else
    echo "Warning: HKASK_HF_TOKEN not set"
fi

# ── Step 3: Run training ─────────────────────────────────────────────────
echo "============================================"
echo "Starting axolotl training"
echo "============================================"
cd /workspace

set +e
axolotl train /workspace/config.yml 2>&1 | tee /workspace/training.log
TRAIN_EXIT=$?
set -e

if [ $TRAIN_EXIT -eq 0 ]; then
    echo "Training completed successfully"
else
    echo "Training failed with exit code $TRAIN_EXIT"
fi

# ── Step 4: Upload adapter to HuggingFace ────────────────────────────────
if [ -n "${HKASK_HF_MODEL_REPOSITORY:-}" ] && [ -d "${HKASK_OUTPUT_DIR:-/workspace/outputs}" ]; then
    echo "Uploading adapter to HuggingFace..."
    huggingface-cli upload "$HKASK_HF_MODEL_REPOSITORY" \
        "${HKASK_OUTPUT_DIR:-/workspace/outputs}" \
        --repo-type model 2>&1 || echo "Upload failed (adapter may still be on the pod)"
else
    echo "Skipping upload (no model repo or output dir)"
fi

# ── Step 5: Write completion manifest ────────────────────────────────────
echo "Writing completion manifest..."
cat > "${HKASK_COMPLETION_MANIFEST_PATH:-/workspace/completion.json}" << EOF
{
  "job_id": "${HKASK_JOB_ID:-unknown}",
  "status": "$([ $TRAIN_EXIT -eq 0 ] && echo completed || echo failed)",
  "model_repo": "${HKASK_HF_MODEL_REPOSITORY:-}",
  "finished_at": "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
}
EOF
echo "Manifest written to ${HKASK_COMPLETION_MANIFEST_PATH:-/workspace/completion.json}"

# ── Step 6: Keep container alive for SSH debugging ───────────────────────
echo "============================================"
echo "Training complete (exit code: $TRAIN_EXIT)"
echo "Container staying alive for SSH debugging."
echo "To terminate: use RunPod console or drain_all_pods"
echo "============================================"

exec sleep infinity
