#!/usr/bin/env bash
# hkask-training-base entrypoint
#
# SINGLE generic entrypoint for ALL training jobs. Reads HKASK_INSTALL_SCRIPT
# (generated by Rust at submit time) and executes it.
#
# ARCHITECTURAL REQUIREMENT: Pods MUST be debuggable. This entrypoint:
# 1. Logs everything to /workspace/logs/entrypoint.log
# 2. Starts a simple HTTP log server on port 7060 so logs can be tailed
#    without SSH (curl http://POD_IP:PORT/logs)
# 3. Ensures SSH daemon is running
# 4. Delegates to the install script for pip install + training + upload
set -euo pipefail

# ── Logging ─────────────────────────────────────────────────────────────────
mkdir -p /workspace/logs /workspace/outputs /workspace/.cache/huggingface /workspace/.cache/pip /workspace/tmp
exec > >(tee -a /workspace/logs/entrypoint.log) 2>&1

echo "=== hKask Training Base Entrypoint ==="
echo "Job ID: ${HKASK_JOB_ID:-unknown}"
echo "Base model: ${HKASK_BASE_MODEL:-unknown}"
echo "Harness: ${HKASK_HARNESS:-undetermined}"
echo "Started: $(date -u +%Y-%m-%dT%H:%M:%SZ)"

# ── Environment ──────────────────────────────────────────────────────────────
export HF_HOME=${HF_HOME:-/workspace/.cache/huggingface}
export PIP_CACHE_DIR=${PIP_CACHE_DIR:-/workspace/.cache/pip}
export TMPDIR=${TMPDIR:-/workspace/tmp}
export PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True
export HF_HUB_ENABLE_HF_TRANSFER=${HF_HUB_ENABLE_HF_TRANSFER:-1}

# ── Start HTTP log server (port 7060) ───────────────────────────────────────
# Simple HTTP server that serves the entrypoint log file. This allows
# training_status to fetch recent logs via HTTP without SSH, and allows
# operators to curl the log from anywhere the pod is reachable.
start_log_server() {
    while true; do
        # Serve /workspace/logs/ on port 7060 using Python's http.server
        cd /workspace/logs && python3 -m http.server 7060 2>/dev/null
        sleep 1
    done &
    echo "=== Log server started on port 7060 ==="
    echo "    curl http://POD_IP:PORT/entrypoint.log to fetch the full log"
}
start_log_server

# ── Ensure SSH is running ───────────────────────────────────────────────────
if command -v sshd >/dev/null 2>&1; then
    mkdir -p /run/sshd
    /usr/sbin/sshd 2>/dev/null || true
    echo "=== SSH daemon started ==="
elif [ -f /etc/init.d/ssh ]; then
    /etc/init.d/ssh start 2>/dev/null || true
    echo "=== SSH daemon started (init.d) ==="
else
    echo "WARNING: No SSH daemon found — SSH debugging may not work" >&2
fi

# ── HuggingFace login ───────────────────────────────────────────────────────
if [ -n "${HF_TOKEN:-}" ]; then
    echo "=== Logging in to HuggingFace ==="
    huggingface-cli login --token "$HF_TOKEN" --add-to-git-credential 2>/dev/null || true
else
    echo "WARNING: HF_TOKEN not set — cannot access private datasets or upload to private repos" >&2
fi

# ── Execute the install + training script ───────────────────────────────────
if [ -n "${HKASK_INSTALL_SCRIPT:-}" ]; then
    echo "=== Executing install + training script ==="
    printf '%s' "$HKASK_INSTALL_SCRIPT" > /workspace/install_and_train.sh
    chmod +x /workspace/install_and_train.sh
    exec bash /workspace/install_and_train.sh
fi

# ── No install script — error out clearly ───────────────────────────────────
echo "FATAL: HKASK_INSTALL_SCRIPT not set — cannot run training" >&2
echo "    The training server must generate and inject HKASK_INSTALL_SCRIPT." >&2
echo "    If using a custom template, ensure it passes through HKASK_INSTALL_SCRIPT." >&2
exit 1