#!/usr/bin/env bash
# hkask-training-base entrypoint
#
# This is the SINGLE generic entrypoint for ALL training jobs — axolotl,
# TRL, Ludwig, or any future harness. It does NOT know which harness is
# being used. It reads HKASK_INSTALL_SCRIPT (a bash script generated by
# Rust at submit time) and executes it.
#
# The install script is harness-specific and contains:
#   - pip install commands for the harness + deps (pinned versions)
#   - Writing the rendered config/script to /workspace
#   - HuggingFace login
#   - The training command
#   - Adapter upload
#   - Completion manifest
#
# This entrypoint just sets up the environment and delegates to the install
# script. If no install script is provided, it falls back to the legacy
# per-harness env vars (HKASK_AXOLOTL_CONFIG, HKASK_TRL_SCRIPT,
# HKASK_LUDWIG_CONFIG) for backward compatibility.
set -euo pipefail

# ── Logging ─────────────────────────────────────────────────────────────────
mkdir -p /workspace/logs /workspace/outputs /workspace/.cache/huggingface /workspace/.cache/pip /workspace/tmp
exec > >(tee -a /workspace/logs/entrypoint.log) 2>&1

echo "=== hKask Training Base Entrypoint ==="
echo "Job ID: ${HKASK_JOB_ID:-unknown}"
echo "Base model: ${HKASK_BASE_MODEL:-unknown}"
echo "Harness: ${HKASK_HARNESS:-undetermined}"
echo "Started: $(date -u +%Y-%m-%dT%H:%M:%SZ)"

# ── Environment ──────────────────────────────────────────────────────────────
# Critical: cache to workspace volume, not container disk (Lesson 1).
export HF_HOME=${HF_HOME:-/workspace/.cache/huggingface}
export PIP_CACHE_DIR=${PIP_CACHE_DIR:-/workspace/.cache/pip}
export TMPDIR=${TMPDIR:-/workspace/tmp}
export PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True
export HF_HUB_ENABLE_HF_TRANSFER=${HF_HUB_ENABLE_HF_TRANSFER:-1}

# ── HuggingFace login ──────────────────────────────────────────────────────
if [ -n "${HF_TOKEN:-}" ]; then
    echo "=== Logging in to HuggingFace ==="
    huggingface-cli login --token "$HF_TOKEN" --add-to-git-credential 2>/dev/null || true
else
    echo "WARNING: HF_TOKEN not set — cannot access private datasets or upload to private repos" >&2
fi

# ── Execute the install + training script ──────────────────────────────────
# The install script is generated by Rust (RunpodHost::submit) based on the
# selected harness. It contains pip install, config writing, training, upload,
# and manifest writing — all harness-specific logic.
if [ -n "${HKASK_INSTALL_SCRIPT:-}" ]; then
    echo "=== Executing install + training script ==="
    printf '%s' "$HKASK_INSTALL_SCRIPT" > /workspace/install_and_train.sh
    chmod +x /workspace/install_and_train.sh
    exec bash /workspace/install_and_train.sh
fi

# ── Legacy fallback (backward compatibility) ───────────────────────────────
# If no install script is provided, fall back to the old per-harness env vars.
# This preserves backward compatibility with existing pod templates.
echo "WARNING: HKASK_INSTALL_SCRIPT not set — falling back to legacy per-harness env vars" >&2

if [ -n "${HKASK_AXOLOTL_CONFIG:-}" ]; then
    echo "=== Legacy axolotl mode ==="
    printf '%s' "$HKASK_AXOLOTL_CONFIG" > /workspace/config.yml
    pip install --no-cache-dir axolotl huggingface_hub
    axolotl train /workspace/config.yml
elif [ -n "${HKASK_TRL_SCRIPT:-}" ]; then
    echo "=== Legacy TRL mode ==="
    printf '%s' "$HKASK_TRL_SCRIPT" > /workspace/train.py
    pip install --no-cache-dir "trl==1.8.0" "peft==0.19.0" "transformers==5.9.0" bitsandbytes accelerate liger-kernel huggingface_hub
    python /workspace/train.py
elif [ -n "${HKASK_LUDWIG_CONFIG:-}" ]; then
    echo "=== Legacy Ludwig mode ==="
    printf '%s' "$HKASK_LUDWIG_CONFIG" > /workspace/model.yaml
    pip install --no-cache-dir ludwig huggingface_hub
    ludwig train --config /workspace/model.yaml
else
    echo "FATAL: No training config found — set HKASK_INSTALL_SCRIPT or one of HKASK_AXOLOTL_CONFIG/HKASK_TRL_SCRIPT/HKASK_LUDWIG_CONFIG" >&2
    exit 1
fi

# ── Keep pod alive for SSH debugging ───────────────────────────────────────
echo "=== Entrypoint complete. Pod staying alive for SSH debugging. ==="
exec sleep infinity
